### ISSUE TITLE
How to behave if a project uses SemVer, but its maintainer is made to show the version of that project in SemVer incompatible format?

### ISSUE THREAD

**Issue by dvorapa** [semver/semver#168]
We call for a little note in the FAQ under the specification clarifying, how to behave when any service requires the 4th (5th, 6th, ...) number from us. My proposal would look like this:

```
FAQ

What to do if any package/app management service requires the 4th number to be filled in?
Just give them zeros and hope they change their opinion one day and let the choice on their users.
```

This issue formerly refferenced two problems. For the second problem where the dependency of the project requires to add its version after the project's one I created separate issue #243 

Please share your opinion with us and think about it ;)

**Comment by JamesMGreene** [comment]
:+1: for this issue, it is especially bothersome for downstream wrappers (e.g. bootstrap-sass, the Node.js module wrapper for PhantomJS, the Node.js wrapper for Adobe/Apache Flex SDK, etc.).

My big fear is that we'll add the 4th place (which I am mostly in favor of) but then _that_ would become standard for upstream libraries, and subsequent the downstream wrappers would need a 5th number, etc.

In light of that fear, I've proposed something a little different in my newly filed Issue #242: **infinite** (_`n_`) optional numeric version segments trailing after the "core" version (`MAJOR.MINOR.PATCH` trio).

**Comment by dvorapa** [comment]
Yes, the issue is still open, but I don't agree with your proposal. We shouldn't change the main core of semver specification, because it is really sophisticated. In my opinion we should just call for a little note or small paragraph at the end of the specification (or in the FAQ under the specification) clarifying, how to behave when any service requires the 4th (5th, 6th, ...) number from us. My proposal would look like this:

```
FAQ

What to do if any package/app management service requires the 4th number to be filled in?
Just give them zeros and hope they change their opinion one day and let the choice on their users

```

**Comment by glebm** [comment]
Bootstrap Sass had to [switch](https://github.com/twbs/bootstrap-sass/blob/v3.3.3/CHANGELOG.md#333) to 3-digit numbers to be compatible with npm and bower. It no longer has MAJOR.MINOR.PATCH parity with upstream. :'(

**Comment by dvorapa** [comment]
Sounds great! Or not? Bootstrap goes SemVer!

**Comment by dvorapa** [comment]
BTW see the updated description and #243 derived from this issue

**Comment by EddieGarmon** [comment]
Your dependencies' versions should not be directly embeddable in your version number, even if you are nothing but a wrapper API.
________________________________

**Comment by glebm** [comment]
It's not great, confused users ensue. :fire:

**Comment by dvorapa** [comment]
@EddieGarmon Yes, they should not. But if Bootstrap begins using SemVer, it should from now add sass number after + letter right? So there is no confuse! Or please explain me better if I missed something.

**Comment by glebm** [comment]
@dvorapa Bootstrap (written in LESS) has always been semver. The Sass conversion of it (a separate package, bootstrap-sass) tried using the plus `+`, but had to drop it because of incompatibilites with bower and npm. The latest bootstrap-sass is 3.3.3, but that corresponds to bootstrap 3.3.2. The next version of bootstrap will be 3.3.4+ and there will be no bootstrap 3.3.3, because that was used by bootstrap-sass. Are you confused yet?

**Comment by JamesMGreene** [comment]
I'm with ya, @glebm. It's a crappy situation but, honestly, even after spending pretty much all day thinking through this and prototyping some alternative schemes, I've arrived at the conclusion that this just isn't _really_ possible because we're trying to represent 2 semi-independent version numbers simultaneously. :-1: :weary:

**Comment by glebm** [comment]
It only "works" for bootstrap-sass because the same team maintains both packages.

**Comment by dvorapa** [comment]
@glebm Just a little bit. Just for reassurance: The `EXTRA` number is still missing in semver spec we want to change. @JamesMGreene That's it. There are at least three usages of the 4th number if I remember. All were discussed in this thread. So there are 3 semi-independent version numbers simultaneously represented by one `EXTRA` pattern. Therefore I've tried to replace one of the usage-cases of the 4th number by tilde pattern (see #243). You could help to clarify its usage, I think I didn't expressed its purpose in the right way. And there could be proposed more than just `~` (like x # / * .. and so on). Let's open the dicussion again!

**Comment by milesrout** [comment]
@dvorapa You don't need an EXTRA number. 

Next!

**Comment by dvorapa** [comment]
No, you sometimes need and EXTRA number, please read the description of this issue at the beginning!

**Comment by FichteFoll** [comment]
The problem in OP has been solved and the solution is even listed there: Just add `.0` indefinitely. There is no need to add that to the spec because everything else than three main numbers is a different versioning scheme and semver can't claim to be compatible with them all, nor provide steps to achieve compatability.

The other issue raised in this discussion is discussed more deliberately in #243, #17 and most recently #242. Similar: #80, #148.

**Comment by dvorapa** [comment]
There is big caveat, that it isn't anywhere in the spec, how to behave, if anybody requires on us anything out of spec. It is needed to be clarified somewhere in the FAQ, because too many questions about these problems are asked on stackoverflow and nobody is interested in adding one more question under FAQ of the semver about how to behave if <the title of this bug>.

**Comment by milesrout** [comment]
It isn't related to the spec and it has nothing to do with the spec. How you wrangle semver into the hundreds of different versioning schemes out there has nothing to do with semver. You want support for four-numbered schemes in semver. Do you also want support for odd-unstable-even-stable schemes, like the pre-3.x Linux scheme? Do you want support for schemes that converge to an irrational number with each new version, like TeX? 

semver's spec is about semver. Can we please leave it that way?

**Comment by milesrout** [comment]
And how is it not completely obvious that you do *whatever you want* with the fourth number?

**Comment by dvorapa** [comment]
1. I don't want to change spec
2. I don't want to handle everything
3. I just want to clarify, how to behave if a project uses SemVer, but its maintainer is made to show the version of that project in SemVer incompatible format (e.g. by dumb package manager, which requires 4 numbers).
4. If you are interested in 4th number or so, you are in the wrong issue...

**Comment by leif81** [comment]
@dvorapa I think zero padding the extra digits as you had suggested is the best and only solution for using a semver in a non-semver environment.

FWIW...I'd lean against semver documenting this case though. People may interpret it as _support_ for four digits which as this discussion shows is like opening a can of worms!

Just zero the extra digits and move on :)

**Comment by JamesMGreene** [comment]
@dvorapa: Seems reasonable and appropriate to add such a note to the FAQ section but definitely NOT to the main spec sections. :+1:

**Comment by dvorapa** [comment]
@leif81 it is worse, like throwing an openned can of TNT into a fire ;-) 
@JamesMGreene Definitely!

**Comment by jedwards1211** [comment]
@glebm that makes sense in your case, but I think it's too specific to become a widely adopted interpretation of a 4th version number.

It may seem like a 4th version number is applicable for all packages whose version tracks the version of an upstream project, but it use is really much more limited.  Imagine a webpack plugin for example; say you want the versions of your plugin to match the versions of webpack.  But what if you want to add a completely new feature to your plugin -- which version number do you increment then?  Or if you make a breaking change in your plugin while still targeting compatibility with the same webpack version?  I think it only makes sense to track another package's version number in cases like yours where your package content is almost entirely determined by the content of the other package, and you know there are going to be no major changes in how you build/convert from the other project.  So the 4th version number would have pretty limited relevance.

**Comment by jwdonahue** [comment]
@dvorapa, unless you intend to pursue this issue further, can please close it at your earliest possible convenience?

It's my opinion that SemVer shouldn't prescribe policy for conversions between itself and other versioning conventions.  There's just too many variables to account for.

**Comment by dvorapa** [comment]
I just asked how to continue with this problem. Yes, becuase there is too many variables to account for and SemVer in my opinion should give some possible solution. Not concretely, at least inconcretely

**Comment by jwdonahue** [comment]
@dvorapa, let's work this one. I've been working the SemVer tag on StackOverflow lately and there are some questions there and here regarding mappings between schemes.  It seems a FAQ would be useful, but I don't think we can provide a simple formula.

How you map the SemVer triple to any foreign versioning scheme is highly dependent on the semantics of the foreign scheme and your own product release policies.   When you enter a version number into a packaging ecosystem, you are committing to whatever contracts are implied by the use of that scheme.  Consider the reverse problem of mapping from the foreign scheme onto SemVer.  Are there any elements in the foreign scheme that imply any of the semantics of SemVer's version fields?  Generally there are none, therefore the entire foreign version number must be shifted right and SemVer's two most significant fields should be zeroed.

Foreign version, semantics unknown: 1.3.7.1248
SemVer: 0.0.1-3.7.1248

It is possible that the foreign scheme has some kind of semantic meaning, but the implied contract is usually so weak that none of them map onto any SemVer number above the 0.0.x range.  So generally, given that SemVer is stronger than most foreign schemes, you have a good bit of freedom, but you should always consider how package dependencies are resolved in the target ecosystem and think through the implications of that, for your own release cycles.  If you shift the semver number to the left in the foreign scheme, will your bug fixes be picked up?  Maybe you can't just shift them, maybe in order to  maximize for your needs, you maintain a completely different version number using the proper semantics of the foreign scheme.  It might be that SemVer's major or minor numbers have some significance in specific fields in the foreign scheme, but the rest of the string just doesn't have any mapping at all.

I don't think we can say "just zero the least significant field".  One possible scenario is that you designate the foreign scheme's most significant field to your marketing department and map the SemVer version number into the middle or right most fields of the foreign scheme.  Or maybe, your SemVer number winds up in the title or description of the foreign system.  Some development processes always include a build meta tag that incorporates a sequential build number, you might want to move that into the the build number field of the foreign scheme.

Can we condense all of that into one or two paragraphs in a FAQ?

**Comment by jwdonahue** [comment]
@dvorapa, unless you require further clarification, please close this issue at your earliest possible convenience.  Thank you.

**Comment by dvorapa** [comment]
There still should be some paragraph in the FAQ

**Comment by jwdonahue** [comment]
@dvorapa 

What could the FAQ possibly say? Always using zero is wrong and so is always using any other number. The right thing to do, depends heavily on how the automation and humans interpret the fields and the changes you've made to your product.  There is nothing the FAQ could say that would be generally correct. Your solution to the problem may work for you, but it's not going to work for everybody.

Why doesn't this competing scheme document the mapping to/from other schemes? Maybe they should at least provide a mapping to SemVer?  Why place the burden on the SemVer spec and FAQ? If it's on SemVer, then which competing schemes should be covered? Google Play and Microsoft Store use versioning schemes that solve a different problem than SemVer, NPM and Nuget coverage makes more sense, but they both support SemVer anyway, as well as their own four digit schemes (or they used to), so where's the fire?

Unless you intend to issue a PR with suggested language for this entry in the FAQ, I don't know who would want to make the attempt. My knowledge of the problem space, suggests it would require an entire white paper on the subject of mappings between version schemes and it has to take a range of development practices into account as well. My gut tells me that persons of average intelligence, don't need us to tell them how to solve this problem, and would probably recognize the fallaciousness of any trivial advise we might give. Unfortunately, there's too many developers out there, who wouldn't be that smart, they'd blindly follow the simple advice given and then complain when they cause millions of dollars of damages due to their ignorance.

Coming from an electronics hobbyist background, I think of this an interface impedance issue. Even in electronics, where their's formulas that can be applied to get you into the general vicinity of where you want to be, it's still a bit of a black art, as there's always trade-offs to be made in terms quality, power, cost, etc. For software interfaces and version schemes, we don't even have a theory to guide us through the problem space.  

What should you do if a tool doesn't meet your needs? Adapt to the tool or find another one.

Unless you intend to issue a PR for this issue, please close it. I'am trying to keep the list of open issues within the realm of what might actually get done before the end of this century, and I don't think this issue is going to lead to any changes.

**Comment by jedwards1211** [comment]
@dvorapa how about "if you need to release software in a store that doesn't accept SemVer version numbers in its versioning scheme, please use your own judgement about what version numbers to use for that store"

**Comment by jwdonahue** [comment]
@dvorapa, unless you intend to issue a PR, please close this issue at your earliest possible convenience.

**Comment by jwdonahue** [comment]
@dvorapa, there's been no motion on this for months.  Please close at your earliest possible convenience.

**Comment by alexandrtovmach** [comment]
👻 👻 👻 
Closed as staled
