### ISSUE TITLE
Spec doesn't indicate whether pre-release labels and build metadata are case sensitive

### ISSUE THREAD

**Issue by jeffhandley** [semver/semver#176]
Let's hope they aren't.  But can we get some clarification as to whether or not they are meant to be?

**Comment by thallgren** [comment]
I'm currently fixing some issues regarding how prerelease tags are handled by the Puppet module manager, which uses the [Semantic Puppet](/puppetlabs/semantic_puppet) ruby gem. I came across the issue of case sensitivity and found my way to this PR. Is this still being considered? It would be very helpful if a conclusion was made and this PR was either merged or abandoned.

**Comment by Haacked** [comment]
A stable spec is important and I don't think this is important enough to warrant a change. As @isaacs pointed out in #177 there's an easy workaround for NuGet to both comply with the spec and keep its current behavior.

**Comment by jwdonahue** [comment]
@jeffhandley, it seems that it was decided not to take the changes on this issue and to continue with lexicographical sort ordering, meaning case-sensitive. Unless you have intend to pursue this further, can you please close this issue?

**Comment by dwijnand** [comment]
imo the issue is still valid because it still "doesn't indicate whether pre-release labels and build metadata are case sensitive".

**Comment by jwdonahue** [comment]
@dwijnand, back in 2014 when this issue was opened, that may have been true, but in the current version, it is quite clear in [clause #11](https://semver.org/#spec-item-11) that the major, minor, patch and prerelease tags are to be used for sorting and that the prerelease tag is to be "compared lexically in ASCII sort order". If you do not understand what that means, you probably have no use for the standard.

The [American Standard Code for Information Interchange (ASCII)](https://en.wikipedia.org/wiki/ASCII) was designed for sorting and efficient exchange of text over low bandwidth communications channels.

@Haacked, this issue should be closed. All related issues have been closed as well.

**Comment by dwijnand** [comment]
@jwdonahue I just re-read the comments and if you look nothing has changed in the wording since 2014:

> compared lexically in ASCII sort order

(in https://github.com/semver/semver/issues/176#issuecomment-33937683)

having re-read I agree with you that that's quite clear in terms of case sensitivity. this issue can be closed.

**Comment by jwdonahue** [comment]
I do agree that case insensitive would probably have been the better choice. I am working on a way to specify the exact semantics of any version string, including SemVer, but life keeps intervening.  See [VersionMeta.org](https://versionmeta.org/). VersionSchema is a work in progress, contact me if you have any interest.

**Comment by jwdonahue** [comment]
@jeffhandley, can you please close this issue at your earliest possible convenience? The current spec clearly states ASCII sort order, which implies case sensitivity.  Changing it at this time would be a breaking change in the spec since many of the most popular packaging tools are already case sensitive. The related PR #276 was closed almost a year ago.

Thank you.

**Comment by isaacs** [comment]
Where this conversation landed is that "ASCII sort order" implies case sensitivity, and that's how it's been implemented.  Since the PR was closed with this conclusion, I also recommend closing this.  If we're going to re-open the conversation, it should be with a specific use case we intend to address where case-sensitivity is causing problems.

**Comment by jeffhandley** [comment]
Thank you all for reviving the discussion to ensure it landed in a good place. I am happy to close this.
