### ISSUE TITLE
SemVer needs to define Version Range Spec syntax/behavior

### ISSUE THREAD

**Issue by jeffhandley** [semver/semver#205]
There are many ways to write out version range specs that control what version of software will be referenced.  The SemVer spec doesn't currently declare how range specs against SemVer versions should be written or how they should behave.  I think this is a gap in the spec that is becoming more apparent and necessary to fill.

Issue #200 is a notable issue where this has come up. Issue #172 is another, where there was a proposal to add 'SNAPSHOT' support into the spec. The 'SNAPSHOT' version is actually one that the consumer knows about but the software itself never actually marks a version as the 'SNAPSHOT'.  It's behavior of how to specify that you want to reference a dynamic version number, giving a hint for which version to select.

There are many different approaches for specifying the referenced version.  I propose that we augment the SemVer spec to declare a standard version range syntax with behaviors clearly defined as well.

**Comment by jwdonahue** [comment]
@jeffhandley 

I have gone back and forth on this one ever since my first non-trivial implementation of a tool that consumes and produces SemVer compliant strings. Initially I had a strong desire to see it in a spec somewhere, but not today.
 
I think the SemVer spec should not get into range specifiers, which seems more like a tool chain implementation detail to me.  Defining selectors for SemVer within the SemVer spec would be a bit like Intel defining which C++ operators were legal on their machines.  As long SemVer has well defined ordering semantics, the rest can be dealt with either as a separate standard or just left to implementations to define.

Keep in mind, that there may be opportunities in some languages to simply use built-in operators. What about packaging tools that already have their own set of range selectors over their own version formats?  It may be easier to drive version string format changes to make existing packaging tools more compliant with SemVer, if they are not also expected to adopt new selector operators.

I for one, want to be able to advertise SemVer compliance while maintaining as much freedom of design choices as possible.  Let's take the various selector concepts and describe them properly in some engineering notes that can be accessed from semver.org and not clutter up a perfectly simple standard.

**Comment by FichteFoll** [comment]
I also mentioned this before, but let me state again that SemVer and a range selection syntax for semantic versions should be separate. Of course, the latter depends on the former, so it probably needs to be updated whenever the former is, but that's insignificant.

This issue (and my draft) haven't seen any attention in recent time iirc, but imo this is still an area that could (or should, rather) be tackled and referenced on semver.org. It will not be the only standard for specifying semantic version ranges, but we should aim to be the *de facto* standard. Just like semver is not the only versioning scheme but a very popular one.

Since it's been over three years since this issue (and the draft) have been worked on, we should take another look at the various selectors other tooling software has implemented and weight their options depending on usability, clarity and spread. For example, I highly doubt we could get anywhere without considering what npm does.

I personally don't have too much time for this in the near future, since it will be quite some work fleshing out a complex spec like this, which will be much more complex than semver itself, but I will gladly provide my feedback to any proposals and hereby declare my earlier draft to be place in the Open Domain for anyone to take inspiration from.

**Comment by jwdonahue** [comment]
@FichteFoll & @jeffhandley, version selectors are like programming languages, we all have preferences, and most of those are standardized somewhere.  There's no programming language standard for the same reasons there should never be a SemVer selector standard.  Document whatever selector standards you see fit to solve whatever problems you need solutions for.  I see no compelling reason to include any of them in the SemVer spec.  If we go down that road, shouldn't SemVer define Dev-Ops platforms and programming languages for developers?

**Comment by FichteFoll** [comment]
> I see no compelling reason to include any of them in the SemVer spec.

Again, this is *not supposed to happen*. It would be entirely separate. Most package managers use their own tooling and implementations of version selectors currently and I believe it would be beneficial to have a largely accepted standard that these implementations could refer to and that would reduce the cognitive load on developers who are switching between different ecosystems with different selector syntaxes.

As oppsed to programming languages, I don't believe you can do that much different with version selectors and it's a comparatively trivial task to reduce this down to a common set of operations (and syntax).

**Comment by jwdonahue** [comment]
So, when there are any foreign specs worth referencing, open an issue to add a link to it.  The title of @jeffhandley's original post is  "_SemVer needs to define Version Range Spec syntax/behavior_".  I think this particular issue should be closed.

**Comment by jwdonahue** [comment]
I would add that anyone can write up a doc on their favorite selector dialect and add it to the wiki pages here.

**Comment by jwdonahue** [comment]
@jeffhandley, unless you have questions or intend to issue a pull-request, please close this thread at your earliest possible convenience.

**Comment by alexandrtovmach** [comment]
👻 👻 👻 
Closed as staled
