### ISSUE TITLE
No rule to define package deprecation or end of life

### ISSUE THREAD

**Issue by hparra** [semver/semver#212]
There is no rule to mark an entire package as deprecated or end of life (EOL).

Such a semver would be useful to communicate one or more or the following:
- the package has been superseded by another package
- the package is no longer developed or maintained
- the package parent software or system is obsolete

Proposed grammar:

```
<valid semver> ::= <version core>
                 | <version core> "-EOL"
                 ... etc.
```

Not sure if `-final` is more or less appropriate. I don't have a strong opinion regarding casing.

I'm willing to propose or collaborate on language to produce PR.

**Comment by jwdonahue** [comment]
Perhaps an EOL tag, could be added that begins with something other than the prerelease tag mark? My view is that build meta should be renamed user data and any semantics, ordering or internal syntax should be left up to the implementer.  Putting EOL in the prerelease tag would be useless because it would have lower precedence than whatever the last non-prerelease version was. 

@hparra, if you are not planning on issuing a PR with proposed changes, please close this issue at your earliest possible convenience.  It seems unlikely that any new fields would be accepted into the standard. Perhaps if the maintainers ever decide to open a 3.x.x branch this issue could be revived then?

**Comment by jwdonahue** [comment]
@hparra, can you please close this issue?  It's not getting any traction.

**Comment by steveklabnik** [comment]
> I do not think this should be part of the version number and rather be handled by the respective package manager.

This is the answer. Semver versions and releases are immutable, so mutating the version string doesn't work. This kind of thing is outside of the purview of semver, and is a job for the particular package manager.

Thanks!
