### ISSUE TITLE
How to deal with major/minor changes on a branched release.

### ISSUE THREAD

**Issue by colinw-calix** [semver/semver#218]
We'd like to understand what the best practices are for dealing with numbering of releases on branches of components.

For example we have a component with versions:

1.0.0
1.0.1
1.1.0 - Included in a distribution. 6.0
2.0.0
2.0.1
2.1.0
3.0.0
3.0.1 - Included in distribution 7.0
4.0.0

The 1.1.0 code is branched to support bug fixes. 
How could the 1,1,0 branch be numbered if it requires a major or minor change ? 
Assuming of course that it cannot take some of the changes incorporated in 2.x or 3.x.

We have assumed that when branch the distribution, we bump the major number. Basically just to make room for minor and patch changes. Is this acceptable ?

**Comment by jwdonahue** [comment]
@colinw-calix 

This is a great question. How you handle branch versioning is a matter of end-user policy that is not and should not be taken on directly by the SemVer specification.  That said, if you are maintaining different versions of the same package, in different branches, that might publish new releases or prereleases, then you are constrained by the SemVer triplet state machine.  

As general rule, any forked branches that will ship versions of the product without changing its name, should never take changes that flip the highest of the version triplet fields that the branch is semantically based off of.  If you have branches for X.Y.*, then the highest changes those branches can take would be patch level changes.  If you have branches for X.*.*, then the highest changes those branches can take would be minor level changes (new back-compatible features). In general, I always recommend at least a branch per major version, whether it is for maintenance or vNext (aka master).  If you have teams that are each working on different new non-breaking features, have them branch off of the appropriate major version branch and select an arbitrary minor number for each of those feature teams.

Example branch names and their uses:
Product.1.x.x    // All new back-compatible features plus any bug fixes.
Product.1.3.x    // Meets contractual requirement for important customer with lots of money.
Product.master // Current head of latest development work, could be 2.x.x or higher.

Or the no master form:
Product.2.x.x   // vNext
Product.3.x.x   // vNext after vNext.

I also like to encode branch names into the prerelease tag as -a.branch.X or -a.branch.X.Y and the commit hash from the repo into the build-meta so that the provenance of any packages generated for QA testing, dogfooding, A/B feature testing, etc, can be traced back to the source.  Then move the branch data to the build-meta when you cut new releases from that branch.

If someone working under Prod.1.2.x comes along with a PR that constitutes a minor or major version bump, tell them to go find the appropriate higher level branch to commit it to.

The above should support all the essential work-flows of any mature organization, including back/forward porting of compatible features and bug fixes to all of the appropriate down/up level versions.

Unless you have further questions, please close this issue at your earliest possible convenience.

**Comment by jwdonahue** [comment]
As a general rule, you should only back-port bug fixes to maintenance branches. The whole point of the 1.y.z branch is to support folks who haven't taken the breaking change to the 2.y.z branch. On the rare case that you feel the need to add a feature to a maintenance branch, there's always room to do so.

Unless you have further questions, please close this issue at your earliest possible convenience.

**Comment by Kcstroman8** [comment]
Trying to program my nerm minor v two help
