### ISSUE TITLE
Create an RFC

### ISSUE THREAD

**Issue by LastTalon** [semver/semver#253]
This may have been suggested before, but this would be great to submit as an RFC itself.

**Comment by bperrybap** [comment]
There are different types of RFCs. Informational RFCs don't really mean squat since anyone can submit an informational RFC about anything including the Easter bunny. Getting something beyond an information RFC is not easy which is why so many things are published as information RFCs.

**Comment by LastTalon** [comment]
Well sure, but that doesn't mean its not useful to have as an RFC. I actually never expected something like this to be anything other than an informational RFC.

**Comment by jwdonahue** [comment]
@LastTalon,  request for comments implies someone will have time to review and respond to those comments.  Are you volunteering?  If so, please submit a PR.  If not, please close this issue at your earliest possible convenience.

**Comment by FichteFoll** [comment]
I disagree that the issue should be closed if OP does not volunteer for this. Someone else might.

**Comment by jwdonahue** [comment]
@FichteFoll, certainly, but when?  It's been two years.  The issue can always be revived when someone has time to pick it up.

**Comment by nowox** [comment]
I agree with this issue. Writing an RFC would give confidence in people to use SemVer

**Comment by FichteFoll** [comment]
People are and have been using semver for years already. I do not think having an RFC will realistically impose more confidence in using it. However, I don't think it'd hurt to have one.

**Comment by steveklabnik** [comment]
We are now using internal RFCs as a means of changing SemVer itself. This issue is about IETF RFCs, I assume.

I'm not aware of any plan to submit to the IETF, and I'm not aware of any desire to by the team, either. That doesn't mean that it would be *bad*, necessarily, but I don't see the cost/benefit ratio making sense. So I'm going to close this as `WONTFIX`, essentially. If there's suddenly huge demand for this, we can reconsider. Thanks!
