### ISSUE TITLE
Non-linear developement

### ISSUE THREAD

**Issue by Ericson2314** [semver/semver#259]
Larger projects usually maintain multiple branches of releases. This is done to offer both stability and flexibility. An example of this would be backporting a security fix to an old release.

It is possible to version the project so that the comparability between releases obeys semver's requirements--in other words so the project can be consumed as if it were versioned with semver. However it is not clear how one should go about doing this. For example:

Assume `1.1.0` and `1.2.0`, `2.0.0-alpha`, `2.0.0` are released. An bug is found affecting all versions. Should I release `1.1.1`? Can I release `2.0.0-alpha2`?

**Comment by FichteFoll** [comment]
Depends on the adaptation of that software. If there is a need to support minor versions, then release `1.1.1`, `1.2.1` and `2.0.1`. If there is a need to support major versions, release `1.2.1` and `2.0.1`. Otherwise, only release `2.0.1`.

Pre-releases do not need fix releases since 2.0.0 comes immediately after 2.0.0-alpha already (assuming this is the latest pre-release). People shouldn't be using pre-releases longer than they need to, i.e. when the next stable is released.

**Comment by Ericson2314** [comment]
But since there are no breaking changes from `1.1` to `1.2`, why should I support the former?

**Comment by jwdonahue** [comment]
@Ericson2314 

>But since there are no breaking changes between versions equal up to minor release, why should anyone support any but the last?

I don't understand that question. Do you still need an answer?  If not, please close this issue at your earliest possible convenience.
