### ISSUE TITLE
Would it be helpful to rename major/minor to break/feature?

### ISSUE THREAD

**Issue by ewinslow** [semver/semver#260]
I feel like there is so much confusion on the interwebs about whether bumping from 1.x to 2.0 is "worth" it or accurately reflects what has happened. Introducing a breaking change for a minority of users that depend on some edge case is not necessarily a "major" release in people's minds, and this trips them up and causes hesitance to really adopt semver.

**Comment by FichteFoll** [comment]
Then you'd refer to the 2.x.x branch as "break 2", instead of "major 2". Not exactly fond of it.

**Comment by crazedsanity** [comment]
In days of yore, it seemed uncommon to go from one major version to the next; the common person (non-programmer) felt hesitance to go to the next major version of an application because they might have to re-learn all the shortcuts and features and such.  There was a lot of PR and such involved with a major version.  

Applications stayed at the same major version for years.  Sometimes even decades.

Then it suddenly became less of a stigma: Firefox had sat at version four-point-something for a long time, then suddenly blew through several major versions.  With no intentions of slowing.  Chrome did the same thing.  Other systems followed suit.

So the "bottom line" is that software changes.  It changes a lot.  Sometimes tiny changes cause massive ripples, and sometimes massive refactorings barely seem to touch the surface.  Don't be afraid of change, embrace it.  Change your code.  Bump your major version.  Be bold.

**Comment by stokito** [comment]
Looks similar to issue #321

**Comment by jwdonahue** [comment]
@ewinslow, perhaps it would, but please close this issue if you have no further questions and do not intend to issue a PR.  This ground has been covered before and is not likely engender any changes.
