### ISSUE TITLE
Add another number to semver

### ISSUE THREAD

**Issue by corysimmons** [semver/semver#340]
People are always afraid to to do breaking changes because it means a major ver bump.

The very-real/valid problem is explained well in this presentation: https://www.youtube.com/watch?v=tc2UgG5L7WM

They typically store up 50 million commits in a separate branch they need to maintain, and then launch all these breaking changes at once.

Why not add a fourth field to semver specifically for marketing purposes?

`1.9999.0` -> `2.0.0.0` could be marketed as "Holy crap! FooProj 2 is here! Check out the migration guide!"

This might be a minor change (from `1.9999.0` to `2.0.0.0`) but the only people who would know that are the people closely following the project.

This would allow for the project to advance & iterate quickly, while encouraging more users to adhere to semver strictly -- directly in `master` in a lot of cases.

I know this sort of change would require package management systems to upgrade and add another symbol for this sort of change, but I think it'd be beneficial:
1. Allow people/projects to get to 1.0.0 quickly (how many years was Node production-ready, but still not 1.x?)
2. Allow maintainers to quickly iterate with breaking changes while adhering to semver and _not_ breaking builds.
3. Allow maintainers to do marketing releases where they educated users on a plethora of breaking changes all at once rather than forcing the user to track/remember every little breaking change along the way.

Let me know your thoughts, but I've been thinking this for years and have heard other people independently wonder why this feature doesn't exist.

SemVer 3.0.0.0 pls! 😻

**Comment by glureau** [comment]
>People are always afraid to to do breaking changes because it means a major ver bump.

I think devs are afraid to do breaking changes for a lot of other reasons, like explaining the breaking changes, documenting how to move from previous to new APIs, the potential bad feeling that could hurt old API users, the management of the transition phase (deprecated API for example), etc.
A breaking change have to be considered as something big when you already have a lot of users used to the "old" API, I don't think it's only on the major var bump.

>Allow people/projects to get to 1.0.0 quickly (how many years was Node production-ready, but still not 1.x?)

As explained earlier, having a 4th numbers would not help them so much: they were probably not sure/happy enough of the API to use 1.x publicly, so I don't think they'll use a 1.0.x to say "you can grab it as a commercial version but it's still not safe/good enough for us".

I'm actually working on a project where we have multiple applications that defines a complete system.  Each app has its specific version, and communication between apps have versionned API, but we used a public commercial name of "2.0" when some new features arrived. That's not impacting how we version our apps, it's purely commercial. (The only thing we wrote at this time was a mapping of all app/api versions, but it was only internal and nobody really used it.)

>Allow maintainers to quickly iterate with breaking changes while adhering to semver and not breaking builds.

That's interesting, but I don't understand how this can work. A breaking change that is not breaking build? What's breaking then? Or you mean about deprecated stuff? In both case, I don't see the relation with the commercial number.


PS: I'm more a Java/Android developer, even if we try to release at least once every 2 weeks, but I understand than requirements for JS devs can be quite different. If you have more examples :)

**Comment by Exadra37** [comment]
This is [why](https://github.com/exadra37-versioning/semantic-versioning/blob/master/WHY.md) I think we need a version number for **_Backwards Incompatible_** changes.

The solution for my personal projects is to versioning like [this](https://github.com/exadra37-versioning/semantic-versioning/blob/master/README.md)  to solve what  [SemVer](https://semver.org) is not addressing.

For PHP Developers using Composer on their projects with Semanting Versioning like `1.0.0.0` will not be a problem as per this [Composer Demo](https://gitlab.com/exadra37-versioning/composer-demo/tree/master).

For some other Programming Languages maybe their Dependencies Managers may need to be updated to handler the 4 digits Semantic Version schema.

So I vote for a  `3.0.0.0` [SemVer](https://semver.org).

**Comment by colomet** [comment]
I like in the @Exadra37 way. 3 digits makes the counter to work to fast and the most of thte times for no reason. Look to wordpress. They use X.X but the security release is X.X.X, because nothing change in the code they do not need to change the 2 digit. 

If we use 3 digits and we have a BUG_FIX, we will increase the 3 digit but nothing new appears in the code, a 4 digit will fix that and the people will understand nothing but security change.

**Comment by jeme** [comment]
This seems to be a recurring subject, and there seem to be a theme of MAJOR.MINOR.PATCH meaning:

- Major: Must mean huge work for me, I used years to get here on my software. I should only increment this when I have put major effort into my software.
- Minor: I have added a feature to my software, small piece of work although it did amount to some time. I should increment this whenever i use a modest amount of time giving something new.
- Patch: I did this in a day!... YAY...

But that doesn't really mean anything to your consumers, you could have used years to rework you entire codebase, but in the end you keept the exact same API and contracts, So it's not even a MAJOR. 
Or you could change a single line and introduce a breaking change....

You have to turn the perspective around, think of packages you consume rather than packages you create, and then look at the version numbers from that perspective... Try to argue about your change from that perspective, and I think you will find that it doesn't really make sense anymore...

As a consumer of a package, having X.X.X.X, the first number doesn't really provide value for me, the first two numbers ends up meaning the same thing to me.... Lots of work ahead... So I don't need 2.

Having multiple versioning schemes isn't really uncommon.

**Comment by colomet** [comment]
I just think bug fixes must be in a different number. Because the last line for backwards-compatible and bug fixes together is a bad idea. 

What is a backwards-compatible? , some times that give us problems. It happen all the time, maybe by mistake but one new feature breack the site once it works with other code together (we work with pressbooks where some plugins can have incompatibilities). But a bug fix, change nothing in the code (don´t use to).

**Comment by Exadra37** [comment]
I am using [this Semantic Versioning](https://github.com/exadra37-versioning/semantic-versioning) approach and my reasons for it can be found [here](https://github.com/exadra37-versioning/semantic-versioning/blob/master/WHY.md).

A proof of concept of this approach working with Composer can be found [here](https://github.com/exadra37-versioning/composer-demo)

**Comment by jeme** [comment]
@Exadra37 IMO it is a bit unfortunate to call that a "Semantic Version" approach, this will only cause confusion as there are expectations associated with SEMVER which is then broken.

Don't get me wrong, I think it's fine that you define your own spec on how you do versioning of your software, but the naming clash is unfortunate I think.

Btw... Isn't your approach very similar to: https://github.com/mojombo/semver/issues/321 ? (What he/she calls Explicit Versioning) - Perhaps it was worth it for you (and others who wan't the 4th number) to collaborate with that?

**Comment by Exadra37** [comment]
@jeme 

I just created my how specification because SemVer does not work properly to handle Software Development.

Sorry to say but SemVer concept is flawed and broken, that is why it has lots of bad implementations and lots of the big players don't use it.

I would prefer to see SemVer adopt the 4 digit :)

I will check that issue you mentioned... Thanks for pointing it out.

**Comment by sapioit** [comment]
**You can look at it this way:**
If you're using random names for your variables, people can and WILL misunderstand what your code does. Sure, even if you use suggestive, explicit variable names, some will still misunderstand them, but their number is insignificant compared to when using random variable names.

And that's why SemVer is broken, forever. It enforces semantics to the point where logic breaks.

**Comment by Exadra37** [comment]
@jeme 

Unfortunately SemVer refuses to accept the reality and all evidences that SemVer is a Versioning Schema widely used in the wrong way, due to is nature of implicit naming in the schema concept.

Sadly instead of seeing SemVer recognizing the reality and evolve to a better schema with 4 digits and release it as `3.0.0.0` a new Versioning Schema was forced to emerge [Explicit Versioning](https://github.com/exadra37-versioning/explicit-versioning/projects/1).

I continue to hope that in future SemVer can reconsider is position.

**Comment by jeme** [comment]
@Exadra37 It's funny how you use "missuse" as evidence for SEMVER being wrong, lets talk down the road when a number of people has adopted EV and you realize that there will always be people using it wrong... You can basically argue that everything in this world is wrong... I used a hammer on a screw the other day, it made a huge hole in the wall and the screw fell out of it!... Safe to say, it didn't go very well so the hammer must surely be wrong! lets redesign it!!!...

For now, I will keep using SEMVER... I don't need 4 numbers where the first two essentially means the same.

**Comment by sapioit** [comment]
No, it might have been the way you hammered it, which is the way you moved from one version of the nail being in the wall to another version of the nail being in the wall.

By not having an explicit enough set of guidlines, you failed to solve the problem you had, and are now blaming the tool (the hammer, the language, the framework, the CMS, etc.) while the problem was following improper guidlines for getting from one stage (version) of the hammer being in the wall to another.

**Comment by jeme** [comment]
@sapioit Or perhaps I had just never read the guidelines and had just seen everyone else swinging their hammers around?

**Comment by colomet** [comment]
@ jeme there are different type of software with differnt needs. Some people need semver, some people need 4 digits

**Comment by Exadra37** [comment]
@jeme 

You haven't even read the Explicit Versioning specification schema that clearly states that the first 2 digits are representing 2 complete different stages in Software Releases.

Of Course you will have always persons using it wrong... you just need 2 persons in a room and a sentence to have a chance off  2 different outcomes. More explicit you write the sentence less difference or no difference at all will come from the interpretation of it. 

And I am not worried about Explicit Versioning popularity related with SemVer, because normally people follow the crowd, aka SemVer, without even know where the crowd is going or if a better path exists.

Remember that is not always the majority that as the reason on their side... 

As I said before **I would prefer SemVer `3.0.0.0` hover having to use another specification** to address the ambiguity in SemVer. 

But as in fan clubs discussions we will not go anywhere, because a fan club person will never recognize the evidence, therefore and sadly I am done here :(

**Comment by jeme** [comment]
@Exadra37 No, i did read them, and they still say: YourScrewed.YourScrewed.YouShouldBeOk.YourOk

> But as in fan clubs discussions we will not go anywhere, because a fan club person will never recognize the evidence, therefore and sadly I am done here :(

It is funny, because your the one who claim that SEMVER is absolutely broken, and that you have evidence...  I i was the one who said I was fine with you not finding SEMVER suiting your needs, so you should perpahs go discuss that "Explicit Version" thing which seemed more aligned to your needs...

So that I am open minded to the fact that you have different needs make me the fanboy?
And that you can't possibly imagine a world where I don't have those needs make you the rational one?

Really?...

 @colomet I have never indicated otherwise.

**Comment by colomet** [comment]
@jeme is a pity, because some of us believe with a modification, we will not need more specifications. One could fit all of us.

**Comment by jeme** [comment]
@colomet thats ok, but the suggestion here adds something some of us don't need, so you would have to work that particular obstacle out before I think it will be accepted into SEMVER. The ideas here are very far from that in my mind.

But sometimes working on the "finished" idea and getting it all down might get you there, so perhaps one day Explicit Versioning will encapsulate both X.Y.X and A.B.C.D schemes and then they can be consolidated, but I think you have some work ahead of you then, either way... Ill encourage you to work together on it rather than apart, so I feel like pointing to Explicit Versioning was the best way to help.

**Comment by Exadra37** [comment]
@jeme 

Firing back on your own words, SemVer says `YourScrewed.YourScrewed.YourScrewed` because not every Software using SemVer applies breaking changes in the same way. They release them in any of the 3 identifiers.

And thanks for pointing out me issue #321 that made us get together to start a new specification that could preferably be adopted by SemVer as the next release `3.0.0.0`.

But keep in mind that I am not wanting to offending you with the fan analogy... I also have fall on the same trap at some points in my live and for sure I may fall again in the future ;)

**Comment by jeme** [comment]
@Exadra37 

> Firing back on your own words, SemVer says YourScrewed.YourScrewed.YourScrewed because not every Software using SemVer applies breaking changes in the same way. They release them in any of the 3 identifiers.

Ohh so in a minute Explicit versioning will be YourScrewed.YourScrewed.YourScrewed.YourScrewed? (You will as a co-author accept the blame of people misusing your guideline?)

SemVer doesn't say that, it's very clear on where breaking changes are allowed to occur, and you should be wise enough to know the difference. There can be two causes here:
 - A) The software you use states it uses SemVer, but introduces breaking changes as you describe, in this case the team is in violation with SemVer, and they should either correct their practices or simply go away from stating they use SemVer, which brings me to option B
 - B) The software you use DID NOT state it used SemVer, but because it used X.Y.Z identifiers for their software, you falsely assumed it used SemVer

Using that as an argument to why SemVer is broken is a rabbit hole someone already tried...
And please don't start the NPM discussion, because that is tiring...

**Comment by Exadra37** [comment]
@jeme 

You made me laugh so loud :)

Explicit Versioning is all about to be **VERY CLEAR WHEN INTENTIONAL BREAKING CHANGES OCCURS**, that is what SemVer is far to achieve, once it mixes Major releases with Breaking Releases in the same identifier, where Explicit Versioning separates that 2 situations into their own identifiers.

And all the rest of what you said just confirms what I been saying, SemVer is ambiguous and open to several interpretations. 

NPM problem is not SemVer versioning schema, is just a immature Package Manager.

Php Composer also relies on SemVer and works fine with 3 or 4 identifiers.

**Comment by jeme** [comment]
@Exadra37 

Did you even ever bother to read the spec for SemVer?... SemVer does not mix Major Release with Breaking changes, it DEFINES it to BE release with breaking changes... 

If you cannot understand this:
Given a version number MAJOR.MINOR.PATCH, increment the:
- MAJOR version when you make incompatible API changes,
- MINOR version when you add functionality in a backwards-compatible manner, and
- PATCH version when you make backwards-compatible bug fixes.

Then there it will be really hard to help you...

**Comment by Exadra37** [comment]
@jeme

Yes I read it and I already posted in this issue several times [the link](https://github.com/exadra37-versioning/explicit-versioning/blob/master/WHY.md) WHY SemVer is ambiguous and mixes major overhauls in your Public Api with intentional breaking changes, please read it.

Now lets's stop here, because this is becoming like discussing the sex of angels... another analogy without offense ;).

I will continue to apply Explicit Versioning to my projects and you SemVer and happy days for everyone :).

**Comment by jeme** [comment]
@Exadra37 Ohh boy... that is where you started...

Let me reiterate my first response in a summary then: SemVer does NOT care HOW big or HOW small a change is, it cares if that change has impact on your USERS/Consumers...

So let me be a little more explicit, your writing:
> Wait, wait and wait... So we need to update the MAJOR from 1 to 2 for the smallest change that is Backwards Incompatible as if we are performing a complety Overhaul in the code?

But that is you that begins to associate the concept "**performing a complety Overhaul in the code?**" with the word "**MAJOR**", but SemVer never did that!...

So it would seem you didn't understand my first response at all... Because i actually state that you COULD do a complete code overhaul without having to change the Major version, all it requires is that you remain backwards compatible...

**Comment by Exadra37** [comment]
@jeme

Quoting like you have is misleading what I have said...

Correct quote:

> So the current SemVer adopts a versioning schema that uses MAJOR.MINOR.PATCH and in a glance it seems perfect.
>
>To add a Bug Fix we will increment only the PATCH version number, like from 1.0.0 to 1.0.1.
>
>When we need to add, at same time, a Bug Fix and a New Feature then both the MINOR and PATCH version number need an update, like from 1.0.1 to 1.1.0.
>
>In the case we have one or both of the above situations, that are Backwards Incompatible, we will need to increment the MAJOR version number and reset the MINOR and PATCH, like from 1.1.0 to 2.0.0.
>
>Wait, wait and wait... So we need to update the MAJOR from 1 to 2 for the smallest change that is Backwards Incompatible as if we are performing a complety Overhaul in the code?
>
>So in my point of view the MAJOR should only be used to go from 1.1.0 to 2.0.0, when a big revolution happens in the CODE and a significant part of is Public Api changes.
>
>For me something to handle changes that are Backwards Incompatible is missing between MAJOR and MINOR.

So now that we have a better context we can see that i refer to an Overhaul in the code as one that introduces major change into the Public Api, that is backwards incompatible, therefore completely different from what you where trying to induce in my affirmations.

Now please relax and enjoy a :beer: and let's continue our lives, unless you want a rant for the eternity :smile:

**Comment by jeme** [comment]
@Exadra37 Ehh... What?... think you should re-read what you wrote then, besides... it changes nothing...

**Comment by Exadra37** [comment]
@jeme 

I don't need to read it again, maybe you should do it again and you will see that at any point I say that MAJOR SemVer definition is not the one you have said:

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
>MAJOR version when you make incompatible API changes,

What I say is that I don't agree with the definition used for SemVer MAJOR identifier and it should be splitted into 2 identifiers.

That said, have an happy day and enjoy the long weekend :sunglasses: .

PS: when visiting Scotland stop by Edinburgh and we will have some :beers: and start another rant in other topic :smiley:

**Comment by krzysiekpiasecki** [comment]
> Allow people / projects to get to 1.0.0 quickly (how many years was Node production-ready, but still not 1.x?)

What's the problem? You can do it as soon as you're ready.

> FooProj 2 is here! Check out the migration guide! "1.9999.0 -> 2.0.0.0 could be marketed as" Holy crap!

And this is good marketing? You sell me your new product, which is still just an improved version of your old product.

**Comment by krzysiekpiasecki** [comment]
> Why not add a fourth field to semver specifically for marketing purposes?

>> 1.9999.0 -> 2.0.0.0 could be marketed as "Holy crap! FooProj 2 is here! Check out the migration guide!"

Software versioning should never be used for marketing. Want to sell me almost the same product as a new?

Introducing an additional number for incompatible changes is just an attempt to circumvent an imaginary problem and is not conducive to software tampering and stabilization. What is the difference if the software has versions `` 1.9999.0`` or ```9999.1.0``` - this is the semversion number.


> Allow people/projects to get to 1.0.0 quickly (how many years was Node production-ready, but still not 1.x?)

You can go to version 1.0 whenever you are ready.


>> Allow maintainers to quickly iterate with breaking changes while adhering to semver and not breaking builds.

Until you're not ```1.0``` you can iterate as fastest as you want. Then you're ```1.0``` and clients expects, that you will not break API. Otherwise you increment major. I can follow your library or stay with old version. If you're care about a client you can mantains old versions too for a long time.

**Comment by sapioit** [comment]
>from my perspective, as a consumer. So I don't need them...

So don't use it, then. Nobody forces you to do so. You can use whatever the heck you want.

>So that I am open minded to the fact that you have different needs make me the fanboy?

No, the fact that you refuse to accept that Explicit Versioning might be the right tool for SOME people makes you a fanboy.

>SemVer does not mix Major Release with Breaking changes, it DEFINES MAJOR to BE releases with breaking changes... 

So what would a Major Release WITHOUT breaking changes be? Like, the exact same code except dropping support for the previous version... It's not breaking anything, and everything works just as before, being the exact same code, with the only differences being the version number and the dropping of support, which, again, does not break anything.

Again, the first number of the 4 represents the version the USERS of the product should care about, with everything else done by the updater of the product.

>Because i actually state that you COULD do a complete code overhaul without having to change the Major version, all it requires is that you remain backwards compatible... 

Except for the developers, where any change can change the way they need to write code. If you add one variable to a function or method, you have to add it everywhere in your code. And more so if the code overhaul changes the system logic of your code.

>Software versioning should never be used for marketing. Want to sell me almost the same product as a new?

Too bad everyone does that. In fact, that's one of the MAIN uses of it's use. The same product, except with this one you can get upgrades, while the previous one will get none.


---

Explicit Versioning is aiming to be both more developer-friendly and more user-friendly. 

Also, I think we should add the usage of 0a.x.x.x (a for alpha, b for beta). And I still think the first number shall be used mainly for dropping the support of previous versions.

And even if you reach 36.x.x.x, what's the problem?

**Comment by jeme** [comment]
> No, the fact that you refuse to accept that Explicit Versioning might be the right tool for SOME people makes you a fanboy.
o.O... I NEVER refused that, I ENCOURAGED you to work together on it...

> So what would a Major Release WITHOUT breaking changes be? Like, the exact same code except dropping support for the previous version... It's not breaking anything, and everything works just as before, being the exact same code, with the only differences being the version number and the dropping of support, which, again, does not break anything.

Your just mumbling here... I can't make any sense of what it is your trying to ask here... To answer what I think your asking:

```JavaScript
// v1.0
// arr: Array of numbers
function meFunc(arr)
{
    if (arr.length < 2)
        return arr;
 
    var swapped;
    do {
        swapped = false;
        for (var i=0; i < arr.length-1; i++) {
            if (arr[i] > arr[i+1]) {
                var temp = arr[i];
                arr[i] = arr[i+1];
                arr[i+1] = temp;
                swapped = true;
            }
        }
    } while (swapped);
    return arr;
}

// v1.1
// arr: Array of numbers
function meFunc(arr)
{
    if (arr.length < 2)
        return arr;
 
    var middle = parseInt(arr.length / 2);
    var left   = arr.slice(0, middle);
    var right  = arr.slice(middle, arr.length);
 
    return innerFunc(meFunc(left), meFunc(right));
    
    function innerFunc(left, right)
    {
        var result = [];

        while (left.length && right.length) {
            if (left[0] <= right[0]) {
                result.push(left.shift());
            } else {
                result.push(right.shift());
            }
        }

        while (left.length)
            result.push(left.shift());

        while (right.length)
            result.push(right.shift());

        return result;
    }
}
```

Say that is some major overhauls of the code right there, actually... In fact it was a complete rewrite of the code... And given the same input you will get the same output... So it is Totally backwards compatible... Amazing right?...

> Except for the developers, where any change can change the way they need to write code. If you add one variable to a function or method, you have to add it everywhere in your code. And more so if the code overhaul changes the system logic of your code.

No no no... There is no Except for anyone... I Assume you mean adding a parameter to a method, and not a (local) variable? - For the sake of simplicity lets not take languages where you can actually do that and remain backwards compatible into account... IF you do this to a public API then your BREAKING backwards compatibility, and so your arguing with a situation which is the exact opposite of the one I outlined... So your remark, except or whatever makes absolutely no sense other than perhaps to demonstrate that you didn't grasp the idea to begin with...

But back to the piece of code above, it shows just HOW massive changes you can make to your code base while respecting your API... And if you hand't figured it out by now, its a sort function, and its' BubbleSort vs MergeSort... And they do the same thing... THEY SORT THINGS!...

**Comment by sapioit** [comment]
A backwards-compatible overhaul can increment the Compatible, or the Release. However, there is also the difference in the workflow, which can break compatibility with the previous workflow. If you switched from MVP to something else, the compatibility is broken because the developers need to adapt to the big change.

By the way, what language is the code in? The function-in-function is not a good practice for programming in general, even through I understand that `innerFunc` is only loaded when `meFunc` is also loaded, but many languages don't have or don't recommend that.

**Comment by krzysiekpiasecki** [comment]
| A backwards-compatible overhaul can increment the Compatible, or the Release.

Or and maybe or. Simplicity is a milestone. When you really need start a new release use organization to achieve a target. New source history, new documentation, new marketing, etc.

For me your release number is just a new product (angular js => angular)


>> By the way, what language is the code in? The function-in-function is not a good practice for programming in general, even through I understand that innerFunc is only loaded when meFunc is also loaded, but many languages don't have or don't recommend that. Not questioning the code, just curious what the language is.

It's a off-topic. In this language (search google by function name) functions are first citizens, so telling is a bad practice is very controversial.

**Comment by jwdonahue** [comment]
@corysimmons, I think if you search for and read some of the many other threads that suggest adding one or more digits to the SemVer, you'll find that SemVer stake-holder sentiment runs against the idea. Some of the proposals are actually worth considering for write-up and implementation as their own competing standards, but none of them really fit well with SemVer.

Unless you have questions or intend to proffer a PR on this matter, please close this issue at your earliest possible convenience.  Thank you.

**Comment by corysimmons** [comment]
>proffer a PR

I didn't read this thread but I'm assuming people aren't into the idea by the thumbs down so why write a Semver 3.0.0.0 spec??

---

Browsing through thread, the arguments against more description in versioning can be applied to Semver2.

My original proposal:

```
Description.
Breaking.
NotBreakingWithSomeDescription.
NotBreakingWithAnotherDescription
```

Semver2:

```
Breaking.
NotBreakingWithSomeDescription.
NotBreakingWithAnotherDescription
```

If semver is gonna be purist with what matters in a versioning convention then deprecate in favor of the much easier/more logically sound comver: `Breaking.NotBreaking`

Another approach would be to simply change Semver meanings to get the best of marketing + relevant information: `Description.Breaking.NotBreaking` <-- this would be nice but would break everything too much... `1.2.3.4` or `1.2` wouldn't break as much stuff.

I do think a marketing version is infinitely more important than two descriptions devoted to non-breaking (i.e. the `NotBreakingWithSomeDescription.
NotBreakingWithAnotherDescription` in semver2) but I no longer expect large projects that aren't maintained by huge corporations to evolve though so happy to close and let us all get back to work.

**Comment by sapioit** [comment]
Actually, I think it does matter where the marketing version goes, because you can't sell `Semver v3` while when looking through the versions list you see `v86.61.3`. Even if that last `.3` is the same, people need to be taught to specifically look for that one. That's why I think the marketing digit should be to the left of the rest, as the dominant digit. So `v3.86.61` would make more sense for someone who did not read the semver documentation in detail.
