### ISSUE TITLE
Leading or trailing hyphen in pre-release or build identifiers

### ISSUE THREAD

**Issue by chrisowensboston** [semver/semver#360]
As written, the spec allows a pre-release or build identifier to begin or end with a hyphen. 

As a result, the following pass the spec:
- 2.1.7--43  (version is '2.1.7';  pre-release is '-43' )
- 2.1.7+-43 (version is '2.1.7'; build identifier is '-43')
Is this intended / desired?

**Comment by FichteFoll** [comment]
The following text is in both the pre-release and the build metadata section:

>Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty.

**Comment by jwdonahue** [comment]
I would not expect to see any humans deciding to use version strings of that form, but I can imagine automation that might produce them, particularly if some config/database field is empty at the time it was generated. The hyphens may actually convey some meaning to somebody. 

Since there is no bug or controversy here, please close this issue at your earliest possible convenience.

**Comment by chrisowensboston** [comment]
Closed as requested by jsdonahue: there is no bug or controversy here.
