### ISSUE TITLE
why minor versions can't make incompatible changes?

### ISSUE THREAD

**Issue by calidion** [semver/semver#365]
Does this mean, angular 4.0 or any other versioned software can not change any api or function during their development?

it is obviously not true.

both major and minor version should be able to  make incompatible apis.

major versions often lead to arhitectural change or upgrade, while minor versions lead to api changes.

the problem is not we change apis in minor versions but packages should not auto upgrading its dependencies to newer versions.

auto upgrading is the reason that causes all problems not versioning.

I do repect the api stability of the all packages, but I think it should not be mandanary.

I think major or minor versions should be free to make incompatible apis while respect the stability of package apis.

**Comment by vearutop** [comment]
If minor version can introduce a breaking change, it means for every minor upgrade a developer should make sure that nothing is broken, often this may require much effort.

This is the purpose of Semantic Versioning: 
 * minor upgrade is effortless, 
 * major upgrades should be rare.

**Comment by calidion** [comment]
@vearutop 

the problem is that semver / npm assumes that every package shoulde auto upgrade minor versions, not that minor versions change their apis.

minor changes or upgrades often lead to api changes and it is inevitable.
but it is unnecessary to upgrade the major version, because these are only minor changes due to some small feature requests or bug fixes or deeper understanding.

the idea on 

* minor upgrade is effortless

are in effect wrong and a misleading of the process of the software developement.

and which leads to constantly major upgrades which is on the contrary to the idea you bear:

* major upgrades should be rare.

so the idea is self contradictory because of the wrong assumption that minor version should be effortless.

currently most node packages are unstable due to the false assumption that minor versions should be effortless and that seems to be a cause for yarn being introduced which use the accurate and exact version for every package installed.

so I think the wrong assumption is the false root for npm and semver.

the very simple way to correct the false is:

1. npm assumes no auto upgrade
2. mannuly upgrade all package versions
3. make no assumption that minor version changes break no apis.
4. enable multiple versions installation for a package.

**Comment by jeme** [comment]
IMO, there are some misunderstandings here...

> Does this mean, angular 4.0 or any other versioned software can not change any api or function during their development?

That is a misunderstanding, the emphasis is that minor version updates are backwards compatible, that does not mean you cannot make API changes, depending on what language/platform your on there are different ways of making API changes that remain backwards compatible, since you mention Angular 4.0 we can assume javascript so lets take a simple example of a function.

```javascript
// v1.0
function add(x, y) {
  return x + y;
}

// v1.1
function add(x, y, z) {
  if(typeof z == 'undefined'){
    return x+y;
  }
  return x+y+z;
}

// v1.2
function add() {
  var r = 0;
  for(var i = 0; i < arguments.length; i++){
    r += arguments[i];
  }
  return r;
}
```

At every step we have changed the API, first we wen't from 2 paramters to 3, then we wen't all the way to any number of paramters. Functionally they are all compatible with v1.0 so it is safe to upgrade.

> auto upgrading is the reason that causes all problems not versioning.

First of all, these are separate issues, because the auto upgrading of packages often results in problems anyways as not all software out there adheres to SEMVER, and as such going from 1.1 to 1.2 may actually break things. So I have come to the conclusion that avoiding auto upgrading is the safest way.

So now the developers has to upgrade, an here comes the benefit of SEMVER, as @vearutop states, whenever we use a package which uses SEMVER, then we know that upgrading from 1.1 to 1.2 are likely to be effortless (this is not always 100% true, some breaks the rules and others are living on the edge), in contrast, if we upgrade from 1.1 to 2.0 we know we should plan on using a portion of time on it, and that is actually very useful.

> I do repect the api stability of the all packages, but I think it should not be mandanary.
> I think major or minor versions should be free to make incompatible apis while respect the stability of package apis.

What your really saying here is that you don't wan't to follow SEMVER, so then don't... No one is forcing you to do so, what is important then is that you don't state that you use SEMVER, as that would confuse your users... And even better, that you then outline what the different version bumps means to the user using your specific software.

> the problem is that semver / npm assumes that every package shoulde auto upgrade minor versions, not that minor versions change their apis.

SEMVER is not a tool, so it doesn't assume anything... SEMVER is a guideline on a way to do versioning... 

NPM does not assume that packages should be auto upgraded, it is instructed to do so, and yes, the default for npm install --save (etc.) is to follow SEMVER, if you have any issues with this you should take this up with NPM and not SEMVER, you can use the --save-exact to override that behavior though which will no use the range operator.

> the very simple way to correct the false is:
> npm assumes no auto upgrade
> mannuly upgrade all package versions
> make no assumption that minor version changes break no apis.
> enable multiple versions installation for a package.

None of these have anything to do with SEMVER though!

**Comment by vearutop** [comment]
`npm` uses version constraints to resolve dependencies, same as most dependency managers for other languages. If you want to stick to a particular minor version you can use `~` [tilde constraint](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1).

> minor changes or upgrades often lead to api changes and it is inevitable.

This is just a semver violation, there is no semver fault in that.

>currently most node packages are unstable due to the false assumption that minor versions should be effortless and that seems to be a cause for yarn being introduced which use the accurate and exact version for every package installed.

Same as above, if the package can not reach stable versioning it is about package, not semver.

**Comment by calidion** [comment]
@jeme @vearutop 

why some of them not able to adhere to  or violate SEMVER?

Because people make mistakes.

semver is too optimistic about human being which makes it unreasonable for a real versioning which is published by human beings who is apt to make mistakes.

as for the example you illustrated, i think we are not misunderstood.

apis can be chaged to due to upgrade, but also can be changed due to previous misunderstanding or mistaken, there is no reason that minor versions should keep their compatibility.

Why I mentioned npm is that npm's versioning system is based on semver, which has causing a lot of problems which you have mentioned mainly on its stablity and reliablity which is due to the false assumption  that minor versions should be compatible.

I think semver is a good example on the progress of how to do the version managment, but not that matured at present, it seems too restrict, and the versioning of software is more of technology and engineering than of science.

**Comment by jeme** [comment]
> why some of them is not able to adhere to or violate SEMVER?
> Because people make mistakes.
> semver is too optimistic about human being which makes it unreasonable for a real versioning which is published by human beings who is apt to make mistakes.

Some chooses not to follow SEMVER, some doesn't know it exists, and yes... Some even make mistakes, but for the last scenario, SEMVER actually puts forth a "process" that solves this, meaning that even if you wanted to follow SEMVER, but by accident released a minor version which indeed DID break compatibility, SEMVER guides you though this.

> apis can be chaged to due to upgrade, but also can be changed due to previous misunderstanding or mistaken, there is no reason that minor versions should keep their compatibility.

I have a hard time seing how the actual API will change due to a fixed mistake, (bug/defect)... The result of the API may change, but here we have to consider "What was the API meant to do" vs. "What did it do". Lets go back to our previous examples:

```javascript
// v1.0.0
function add(x, y) {
  return x - y; //WOOPS...
}

// v1.0.1
function add(x, y) {
  return x + y;
}
```

Obviously this changes the outcome changes, `add(40, 2)` return 38 in v1.0.0 and then 42 in v1.0.1... So is this a breaking change?... No, as it promised you to return 42 from the beginning. So it was always meant to do so, ofc. more complex examples makes a discussion about this more unclear, but what matters for compatibility to me is what the API promisses you to do, and if it does something different because of a bug, then that is fixed in a patch version.

If your API changes due to upgrading a depending-component, SEMVER will even help you here, if the depending component upgrade was a major, then you need to figure out if your software should also do a major (if you publish using SEMVER)... The safe bet is that you do a major bump as well, it might not seem as a major change to your package, but if you expose stuff from that other package it is a major change to your package...

But this is a much more complex discussion which AFAIK is taking place somewhere else.

> I think semver is a good example on the progress of how to do the version managment, but not that matured at present, it seems too restrict, and the versioning of software is more of technology and engineering than of science.

If SEMVER should have any value to it, then it has to have some rules, otherwise we might just as well delete it and go back to nothing (insanity)... SEMVER puts forth a direction on versioning, and for API's IMO a good one because it brings some structure to how we manage packages and dependencies.

If you wish to follow that is really up to you, and yes, mistakes are made but if you at one point violated SEMVER, it's more important that you know how to correct that violation and not as much that it happened.

**Comment by calidion** [comment]
consider such a situation :

```
// v1.1.0
function fetch(url, cb) {
}
// v1.2.0
function fetch(url, options, cb) {
}
// v1.3.0
function async fetch(url, options) {
}
```
the purpose of fetch is not changed, but the paramters are changed.
but because this is a very minor change to the package, 
we don't no need to upgrade the major version.

it is good to keep in mind that trying to avoid breaking changes, but it should not be assumed that no breaking changes could be made.

**Comment by vearutop** [comment]
@calidion 
`v1.2.0` is an obvious breaking change
`v1.3.0` is a breaking change too

**Comment by calidion** [comment]
@vearutop 
yes. they are.
But should I upgrade packages just because of such small changes?
I don't think so.
normally big changes are accumulated by small changes over time, not by design.
we are not gods to be able to predict everything that is not happening.

**Comment by vearutop** [comment]
To me these changes are big and require a strong justification to exist.

**Comment by calidion** [comment]
My example is a very simple one, but changes from real projects are much more complicated than this one.

I am not saying we should encourage making breaking changes, but that breaking changes should be considered and allowed.

**Comment by calidion** [comment]
@vearutop 

breaking changes are always causing problems or uncomfortableness, regardless of major or minor versions.
as a pacakge maintainer, your duty is to produce a well tested, well coded and stable packages and let old user unaware of changes when the client users' pakcages are tested and passed with your certain version. 
Upgrade or not is not a concern of the maintainer but the client programmer, the client programmer choose to upgrade or not when he sees these changes.
obviously npm(semver based package management system) is bad at giving this right to its users.
npm assumes that all packages should be upgradable within minor version changes.
and its users are suffering from such assumption which makes the whole system very unstable.

it is good to have such rule in mind that minor changes should be compatible.
but it is not in accordance with the fact that we make mistakes and change never get rid of keep making.

so the basic assumption for semver is not true.
and it leads that npm is constantly causing problems due to the false assumption.

**Comment by klehelley** [comment]
I feel like, in the current discussion, the intent of SemVer is not sufficiently taken into account.

Say I am a user of an API that follows SemVer. This is my workflow :

- I see a new PATCH version is available. Coming from the previous version, I expect to be able to just bump the dependency and my code still compiles, all my tests are green, and I may have performance improvement or bugs that I did not know affected my code as a bonus. Effort : negligible.
- I see a new MINOR version is available. Coming from the previous version, I expect to be able to just bump the dependency and my code still compiles, all my tests are green, and I may have performance improvement or bugs that I did not know affected my code as a bonus. I may have warnings if parts of the API have been deprecated, and I may be offered additional tools by the API that may be worth using. I may plan some changes following that. Effort : minimal.
- I see a new MAJOR version is available. Coming from the previous version, by bumping the dependency I may be lucky and have everything working at once, say because I used a subset of the API that did not change. But I may also have code that does not compile anymore, or a lot of red tests. One thing is for sure : the likelihood of my code having to change to accommodate the new version of the API is high. Effort : notable.

This, in a nutshell, is what SemVer brings to me as a user of an API.

If breaking changes are allowed for new MINOR versions, then what is the difference between MAJOR and MINOR? Maybe there is one, but that rationale is out of the SemVer specs, and thus one cannot pretend to just use SemVer while managing their version numbers this way.

In the current discussion, I fail to see a compelling argument in favour of allowing breaking changes with MINOR versions. Doing so would make version numbers less useful than SemVer allows them to be IMO.

**Comment by jeme** [comment]
> breaking changes are always causing problems or uncomfortableness, regardless of major or minor versions.

This would be more an argument for SEMVER as is than against because it helps you to identify when your facing those situations much clearer.

> Upgrade or not is not a concern of the maintainer but the client programmer, the client programmer choose to upgrade or not when he sees these changes.

I would most certainly disagree, the "client programmers" are your "Customers", I would hope you take good care of those or they will go else where. That might be a non-issue if your package is just a small piece of fun your having, but then you can just throw versioning out the window all together as you don't really need it.

> obviously npm(semver based package management system) is bad at giving this right to its users.
> npm assumes that all packages should be upgradable within minor version changes.
> and its users are suffering from such assumption which makes the whole system very unstable.

No, that is incorrect, NPM lets you control this (I already stated that previously), yes the npm install --save defaults to the version range selector, but that can be changed so that it always selects the exact version... I do that lots of times... And just to state it again, if it is a problem, then that is not a problem with SEMVER... but with NPM...

> it is good to have such rule in mind that minor changes should be compatible.
> but it is not in accordance with the fact that we make mistakes and breaking changes can never be get rid of. so the basic assumption for semver is not true.
> and it leads that npm is constantly causing problems due to the false assumption.

And again incorrect, say you introduced a breaking change:

```javascript
// v1.1.0
function fetch(url, cb) {
}

// v1.2.0
function fetch(url, options, cb) {
  if(typeof options == 'function') {
    if(typeof cb != 'undefined') {
      throw 'something'; 
    }
   cb = options;
  }
  ...
}

// v1.3.0 - Breaking
function async fetch(url, options) {
}

// v1.3.1 - Restore optional cb and call it on promise fulfillment - stale this branch.
function async fetch(url, options, cb) {
}

// v2.0.0 - forward 1.3.0 implementation to v2.0
function async fetch(url, options) {
}
```

People using NPM version range selector would automatically get the fixed v1.3.1 which restores compatibility with v1.2.0 (Alternatively you could just have restored v1.2.0 as v1.3.1, although being ugly, it fixes the issue for users). And then it correctly published the breaking change as v2.

Regardless... Using the fact that people making mistakes to remove a rule is like arguing that we should remove a law because someone breaks it... Say like removing the speed limit on roads?...

I feel that your mostly arguing on an issue that really comes from:
 - The default behavior of npm install (--save??) being to use a SEMVER based version range selector.
 - And the fact that not all packages in NPM actually follows the guidelines given by SEMVER, either by choice or by mistake...

And to solve this problem you wan't to change SEMVER?... You do realize that that wont take any effect at all until NPM then updates it's version range selector functionality, in essense deleting it... Which would be the exact same situation as if you just didn't use it to begin with... right?
And then it would leave you much worse of when you finally did deside to update your packages because you wouldn't even have any hints to the effort required at all... right?

So I don't get it... I just don't...

**Comment by calidion** [comment]
@klehelley 

so how do u explain why currently npm packages keep breaks?

your idea of keep your testing green is good, but it still breaks very often.
not the package maintianer is unaware of the goodness of semver, but versions are always breaking just like testing failures.

semver and npm version management doesn't promise the stability of a package. so even the restricted rules exists, you should be wise enough to keep in mind that human beings tend to make mistakes.

these rules are good wills no realities, that is why I would like to point out.

even the PATCH cloud be broken.

the only thing that causes problems is auto upgrade.

you needs no upgrades when you packages are working.

if there is no auto upgrades, packages will never get wrong dependent packages.

so the wrong assumption caused the wrong rules, then caused the wrong version system, then caused the package breaks.

it is nothing to do with the compatibility of patch, minor or major versions.

it is no need to discuss what the semver is and what it should be expected.
because the reality has been neglected at the first place.

the assumption that people don't make mistakes is not true.

it is right we hope most packages are stable at most time, but there are occasions they are not. and these occasions causes breaks too, regardless of major, minor or patch version changes.

so how can anyone keep rules surely be broken someday, sometimes?

**Comment by calidion** [comment]
@jeme 

there is no auto fixing.
it your packages are wrong on something that the client programmer needed.

your packages are rejected at the first place.

as a client programmer, the thing i needed is never bother me again when my programs are tested and working, keep all things intact and same.

every wrong assumption on compatibility leads to a risk that i would spend more time to look into new problems which means money and time.

**Comment by jeme** [comment]
> the only thing that causes problems is auto upgrade.

SEMVER is not auto upgrading anything...  So your problem is elsewhere... And I hate to sound arrogant, but i Think this is mostly because you don't understand NPM fully yet.

**Comment by klehelley** [comment]
@calidion I come from a Java background, using Maven everyday, where auto upgrades is not a thing. I have yet to use NPM, but judging from the previous posts in this thread, while auto upgrades can be a dangerous thing, they can be deactivated if needed. So I cannot say much about NPM. However, if NPM is conceived so that the packages it manages have to follow SemVer, and some developers completely ignore that fact, whose fault is it?

Just to put things back in perspective, what you basically claim at the moment is that, in its current form, SemVer is broken.

Nothing wrong with pointing out that SemVer does not work where it is intended to. Actually, this is encouraged so that the specs can be improved and be useful in all the target cases. Though it has to be made clear why it is SemVer that is broken, in the cases described.

SemVer is but a tool, with rules designed to work in a given context, in order to give useful guarantees. It describes a numbering strategy when releasing APIs, nothing less, nothing more. But as with every tool it can be badly used, be it by applying in the wrong context, or by following only some rules and not others.

A small aside about mistakes: people do mistakes, all the time. Hence the need for a PATCH number, bug trackers, etc. But "some people do not follow SemVer" or "some people follow SemVer, except with some versions from time to time" is not really enough of an argument to say that it is broken. However, if you could demonstrate that people who should be following it do not because of a problem with the specs, now we can talk.

In the present case, it looks like your problem is with NPM and some of the dependencies you are managing with it. Were the people behind NPM right to assume that SemVer would be used most of the time? Maybe, maybe not. The best thing to do is to check whether a justification is given in the NPM documentation, and if not found ask the NPM community.

**Comment by calidion** [comment]
@jeme 

auto upgrade is due to the assumption that minor versions should be compatible, semver is the source for that problem.

And it is being conviced that auto upgrade is not right and at lease problem causing. as a sequence the rules from semver is also not correct, and it is good to embrace the practise that the compatibility should be recommended and keep aware of the possible breaks which are inevitable.

**Comment by calidion** [comment]
@klehelley 

yes.  that is why maven is better in keeping package stability than npm due to no auto upgrade and the semver idea.

semver is a tool and a good try on version management and semver draws a very good vision on how version updates should be.

but it is not realistic and applicable.

even if you keep compatiblity in mind, you can not say that your will not making breaking changes, not just apis paramters, but aslo the logics inside.

it is not that everyone likes to break rules, it is that breaks just happen.
 
I am not saying that we should not keep apis stable, what am saying is that it is not possible to keep such stability all the times. if you take that assumption, you are pushing your self into that risk of package unstability.

so the assumption is not true.

if the basic assumption is not true then all the subsequential rules cannot be true.

that is why node projects brokes constantly when you make a new  `npm install` .

it is not a problem of the package creators/maintainers, it is the problem that npm based on a wrong assumption.

so the semver is somewhat misleading.

and npm is a perfect example for such misleading.

the solution for that npm problem is very simple: 

1. assume no compatiblity on version changes.
2. stop using version range and auto upgrade.
3. stop pushing package users to upgrade.

the idea of upgrading or auto upgrading is not good, which may make versioning somewhat meaningless.

versions are releases you can fallback for when mistakes are made.
who dare say his next version is always better than his previous version?
if not, why should you always auto upgrade to a new version?

**Comment by klehelley** [comment]
Your last post has achieved to convince me: you have gripes with NPM and the fact its assumptions are not widely shared amongst the Node community.

Nothing here to do with SemVer.

> even if you keep compatiblity in mind, you can not say that your will not making breaking changes, not just apis paramters, but aslo the logics inside.

The logic behind the API should follow the rules laid out by the API. Thus, unless there is a bug somewhere, or the rules the API plays by are too loosely constrained, two different versions of a library implementing a given API, in a similar context and given the same arguments should provide the same results. There may be a whole system with lots of moving parts behind the API, and a lot of things could change in-between two versions. But as long as these two versions implement the same version of the same API, you should be able to use one or the other without having to change your code.

> I am not saying that we should not keep apis stable, what am saying is that it is not possible to keep such stability all the times. if you take that assumption, you are pushing your self into that risk of package unstability.

Do note that SemVer does not say anything about the frequency of MAJOR releases. If for a given project someone feels like making breaking changes to their API and releasing them several times a week, SemVer is fine with it as long as for each of these versions the MAJOR number is increased. Of course, this is unrealistic since, with such a frequency of change, who would want to use that API? But then, that is a problem with the API designer, not with SemVer.

> it is not a problem of the package creators/maintainers, it is the problem that npm based on a wrong assumption.
> 
> so the semver is somewhat misleading.

Huh? I fail to see any link between these two statements. "There is a problem with NPM, let's conclude that SemVer is broken." How is that logic?

**Comment by jeme** [comment]
Your running in circles and using the same arguments over and over again... It won't help.

> auto upgrade is due to the assumption that minor versions should be compatible, semver is the source for that problem.

If a package truly follows SEMVER, then tat assumption by NPM is actually correct, but it doesn't just help NPM, it also helps me... But again, this is at BEST a bad default behavior, and if you think so, go here and create an issue: https://github.com/npm/npm

And please try to realize that you can disable this behavior... How many times do I have to state that?... 

> And it is being conviced that auto upgrade is not right and at lease problem causing. as a sequence the rules from semver is also not correct, and it is good to embrace the practise that the compatibility should be recommended and keep aware of the possible breaks which are inevitable.

This is a silly argument, again because people don't follow the rules we should change them?... That makes no sense at all... It also means that we can literally delete every single "Best practice" there is out the because there is bound to be someone who does not follow them...

So i say again... Your problem is here: https://github.com/npm/npm

**Comment by calidion** [comment]
@klehelley 

if changes to affects nothing, why should these changes be made and released?

@jeme  

I have searched npmjs.com

https://www.npmjs.com/search?q=maintainer:jeme&page=1&ranking=optimal

with no package.

I don't know why you are so sure about your idea?

I am wondering if you ever released a package.

**Comment by klehelley** [comment]
@calidion 

I never said nothing had to change. Behind a single version of an API, a lot of things can change: bugs can be fixed, architecture can be improved (for example to improve performance), back-end technologies can be replaced. Even the language used can change!

But of course, it can only go so far. At some point one will want to add functionalities, resulting in an evolution of the API, and this a change in version number. The importance of the change and its consequence in the version number, if SemVer is used, is the responsibility of the code maintainer.

**Comment by jeme** [comment]
With the thing I am talking about, I don't have to have released any NPM packages, I just have to have consumed them...

But I have never released anything under jeme no... That said, I have mostly released though BOWER, which also supports semvers.

Either way, in order to point to a FIXED version with npm, it is on the consumer of a package, after all the package publisher should not be the one making the choice on how the consumer wishes to update, http://stackoverflow.com/questions/33343533/update-npm-package-with-fixed-dependency-from-command-line

The only constructive thing I can add is that maybe it would be a nice addition if a package provider would define "semver: true|false" in the package.json file in order to tell NPM weather or not the package used this scheme...

**Comment by calidion** [comment]
@klehelley 

an good example is angular 1 that made some breaking changes.
but it did not upgrade to angular 2 or above.
the idea of not making breaking changes to minor version are not realistic and misleading.

react is the joker who makes major version meanless and now its version has reached 15 from its former version 0.x.x.

major version changes means you have made a significant changes to your products, not some minor breaks.

if major versions are changed due to some minor breaks, then such major versions are meanless.

**Comment by vearutop** [comment]
@calidion why do you insist on your totally invalid and irrelevant to sevmer point? Is it a troll?

Semver is not the only versioning model available, making major bump for architecture upgrade is something about marketing, like `half-life 1` and `half-life 2`, it has nothing to do with breaking changes or dev efforts.

Meanwhile semver is all about dev efforts on upgrade. 

If angular uses major version to tag new architecture instead of breaking changes, it just means that angular does not follow semver (and you should not expect semver behaviour from it).
Having breaking changes within one major means they failed to design it properly.

There is nothing wrong with react having `v15`, it is still better than having `v2.2` and no idea if it is compatible with `v2.1`.

If you are concerned with too many major versions, semver has a `v0` concept.
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

In the end it is YOU and no one else who should take care of your app, setup dependencies with fixed or range versions, and make sure app is healthy after any deps upgrade.

**Comment by calidion** [comment]
@vearutop 

it is wrong to say that angular fails to design properly.
if angular is wrongly designed, then there is no software ever properly designed.

it is even wrong to say breaking changes should result in a major version.
`v0` in semver is also an example of violation from what semver is proposed.

if semver is correct on its prospect, there is no need for `v0` because every breaking change should result in major upgrade.

**Comment by jeme** [comment]
SEMVER is not a universal truth that all must follow... It is a merely ONE way of doing versioning, one that perhaps happens to have been adopted by many, but that doesn't mean there isn't others out there...

In fact, go give a star to this guy: https://github.com/bshanks/sdver seems your more in par with where he is going... And then go and try to see if you can convince NPM to switch to that instead... (Issue link please so I can down vote)

On the Angular Topic...

AngularJS does NOT state that they use SEMVER, so it is WRONG for you to assume they do.
Your probably confused because they adopted SEMVER for the "new framework" back in 2016. http://angularjs.blogspot.dk/2016/12/ok-let-me-explain-its-going-to-be.html

And yes AngularJS is not badly designed (i use it and I have released a number of modules for it)...

BUT they did make a huge mistake when they introduced a entirely new framework and tried to to push it as just a 2.0. This caused a major uproar in large parts of the community and lead to them having to continue support and development for Angular 1.X (Or what we now know as AngularJS)... So now AngularJS can't even adopt SEMVER if it wanted to, because they cannot bump the version to 2.0 because that would be totally confusing... So yes... They made a HUGE mess of things... THAT DOES NOT reflect the quality of the software it self...

And i am with @vearutop here, this looks far more like trolling than any sort of constructive conversation.

**Comment by calidion** [comment]
It is lucky that angular 1 is not following semver.
so we can clearly feel the differences between angular2 and angular1.
but angular 4 is a wrong choice because it seems angular 4 is no much difference from angular2.
it introduced confusion to the client users and make major version meanless.

**Comment by calidion** [comment]
if angular is to obey semver, then you will find angular 20.x in less than one year or you will not get instant fixing due to version control where some bugs will break.

**Comment by vearutop** [comment]
> And yes AngularJS is not badly designed (i use it and I have released a number of modules for it)...

It is not about how you feel, it is about facts. If you can not update/improve implementation without breaking contract it means your contract had a design flaw (limiting you in some aspect).

It is like by poorly designed contract you expect person name in ASCII, but later you realize Chinese names existence.

If Angular 1 had a perfect design, we would never see Angular 2. If Angular 2 had a perfect design, we would never see Angular 3, 4.

Of course it is next to impossible to produce a perfect design for a complex thing, that's why we have semver v2 (and v3 on the way). But it does not invalidate the fact that breaking changes usually is a sign of incomplete/poor initial design.

**Comment by calidion** [comment]
it is the client programmers' duty to choose proper versions while all software will inevitably release bad versions even where semver is restrictively executed.
this semver rules are set for gods, not for human beings, it is theoretical not practical.

@vearutop 

we should never have perfect design.
perfect means no more developement or envolution, that is not the real world.
In real world, we develope and we correct, some times we destroy.
nothing should be perfect at first, we just develope.
semver is not perfect either.
in effect, you are constantly breaking your logic.
if semver is designed to make a perfect design, it is wrong at the fist place.

but semver do demand perfect.

it assume that fixings and minor changes should never break which is totally a lie.

so semver is harmful to version control when it is adopted by more and more people.

**Comment by jeme** [comment]
@calidion The team has stated that they will adopt SEMVER, deal with it... 

@vearutop It would be bad to deal in black an whites, AngularJS would never have been so widely adopted had it been badly designed, at it's time it was one of the best designed JS/HTML MVC/MVVM's of it's time if we where to take adoption and community growth as any indication. That not the same as saying it's perfect or can't be improved, but claming that something is "Bad design" just because new iterations are released or that new frameworks are invented is evidently the same thing as saying that everything is badly designed as everything evolves, And then that also ends up going for SEMVER, as new Versioning ideas emerge for better or worse.

Angular is a strange piece because the team literally wrote a new framework from the ground up and advertised it as Angular 2.0... If it had all the old concepts there just in a better architecture, then fine, but there is almost no remnant of AngularJS left in what is now just called Angular. While AngularJS is perhaps trying to move towards Angular so that people eventually can upgrade to it effortlessly, it will never be viewed as the same framework by many.

AngularJS is still widely adopted and is getting new releases over time....

**Comment by vearutop** [comment]
@jeme I've never said any Angular had a "Bad Design", and I have nothing against improving architecture with breaking major versions.

If something has the best design now it does not mean this design will be still good after some time.

But if you need breaking changes within current architecture it means (even if your architecture is piece of art) that you missed something in the design and now you need to break things to make them better. It is ok, even best things sometimes suck.

**Comment by calidion** [comment]
I would like to say that `breaking changes should be avoided during the process of development, but it cannot be prohibited`. That is a more realistic rules.

I would like to come up different effortless advices:

1. never update your versions until you really need to. (save your time checking updates)
2. never assume newer versions are better and with no breaks. (save your from upgrading and breaks)
3. bear api stability in mind and try to avoid api changes as possbile. (keep your package in good state)
4. major versions mean architecutre changes (make your change more elligible)
5. minor versions mean feature additions and bug fixings and minor api changes.(make your version evoluable)
6. there is no need to keep a non breaking major version, it is false, cheating, confusion introductory(as angular4 is almost the same to angular2, which may confused you from why you should upgrading).

the thing that is wrong from the ground is that some one assume packages should always be upgraded automatically and it is the duty of a releaser that keep all client software working due to auto upgrade.

so semver is a result of that lie or false, which will lead to major version booming and prevent features and improves being added as a whole to the software or packages.

**Comment by jeme** [comment]
@vearutop We can agree to disagree then... 

What we can build now is constrained by the technology we have available, as that evolves our software have to keep up, Promises is probably a good example of a thing that evolved large parts of how we dealt with async patterns across JavaScript frameworks, that didn't make the passing callbacks to functions a bad design IMO, as that was a patter that emerged before Promises was available. And we will likely see the same thing happening when the next version of ECMA is completed.

Passing callbacks is perhaps wide accepted as a bad design today, but it was the best thing we could come up with at the time as we didn't have any viable alternatives.

Disruptive technology means that we will have a hard time avoiding breaking changes sooner or later. Smartphones has also meant that we had to rethink how we develop web applications etc. in general... Smart devices will also make us rethink... But we cannot design for these things before they exist...

**Comment by calidion** [comment]
@jeme

what if semver is  a bad design?
npm follows semver to be the most unstable package management system ever:)

**Comment by jeme** [comment]
@calidion I am done with you, your running in circles, and refuse to realize that your problem is with NPM and what they have adopted, so this discussion is utterly pointless...

**Comment by CyrilWork** [comment]
Don't waste your time and energy, this topic has enough information already. Thank you jeme, vearutop for nice explanations.

**Comment by junjun77** [comment]
you need to stop guys, i already know.  if you don't stop,  💄 i'll put this in your lip. you know what i'm saying. thank's

**Comment by jwdonahue** [comment]
Please close this issue.
