### ISSUE TITLE
Document should be written in 3rd person, passive voice

### ISSUE THREAD

**Issue by dinamicoplus** [semver/semver#384]
I have noticed the entire document is written in 1st person. I find this strange because the text aims to be a standard and it feels very informal if it is written the way it is. I know maybe because it is a recommendation and not a proper "formal text" but even though I think it should be rewritten in 3rd person.

**Comment by daanhaitsma** [comment]
I completely agree. Was very surprised to read "I propose a simple set of rules" in a document like this.

**Comment by Speldosa** [comment]
Well, I don't have any problems with this with regards to the text's formality. However, examining all the approved pull requests, I don't know if you can say that this document has been authored by an "I". Maybe "we", but that might sound strange, so I agree that it should be rewritten in the 3rd person.

**Comment by jwdonahue** [comment]
@dinamicoplus, are you volunteering to issue the PR for these changes?

I don't find the first person particularly troublesome in an introduction to a specification.  Seems rather routine to me. In fact, "I propose a simple set of rules", has been in the spec since the 1.0.0-beta and as far I can tell, you're the first person to call it out as an issue.  I certainly wouldn't object to changing it. 

In case, please issue a PR or close this issue at your earliest possible convenience.

**Comment by aaaidan** [comment]
I think this may have been resolved, at least in part, by da15534d.

**Comment by JohnTitor** [comment]
> I think this may have been resolved, at least in part, by [da15534](https://github.com/semver/semver/commit/da15534d3511bcb23a03e23a3edeec18d0d06a51).

Closing in favor of the above comment. Let me know if there's still an issue.
