### ISSUE TITLE
The semver.org website should have HTML anchor IDs

### ISSUE THREAD

**Issue by pboling** [semver/semver#422]
So that references can be made directly to a specific point of the spec, to facilitate communication.

**Comment by FichteFoll** [comment]
new_tasks = (self.loop.create_task(coro) for coro in new_coroutines)

**Comment by FichteFoll** [comment]
So, loading the javascript fails because it's using http. This regressed in the following PR where the URL was changed to `{{ site.github.url }}/js/anchorli.js` instead of `/js/anchorli.js`. I'm not sure where this `site.github.url` value is defined (there's an entry in `_config_local.yml`, but I presume it's redundant and also empty).

https://github.com/semver/semver.org/commit/0fda15421a777e33fcb83453d8c0e0a8021e1f6d#diff-2c19d9859b055d0302043d0fa2833e3fR44
