### ISSUE TITLE
Character list for prerelease does not include "." but the examples for it do

### ISSUE THREAD

**Issue by DarwinJS** [semver/semver#435]
Thanks for maintaining the semver standard!

On semver.org item 9 and 10 do not show "." in their list of valid characters allowed after a dash (pre-release).  However, the examples do show a "."

I know of at least one significant implementation where this ambiguity may have led to validation routines that do not allow a "." after a "-" when evaluating a sem version.

Although "." is implicit to the format, since pre-releases are an exception case, it would be nice to make the "." explicit in the character list if it is valid.

**Comment by jeme** [comment]
The identifiers are not allowed to have "." in them because they are individually separated by ".".

Quote on 9: A pre-release version MAY be denoted by appending a hyphen and a series of **dot separated** identifiers 

Quote on 10: Build metadata MAY be denoted by appending a plus sign and a series of **dot separated** identifiers

**Comment by DarwinJS** [comment]
Thanks for explaining - I read quickly and was thinking a "prerelease identifier" was referencing everything after the first dash.
