### ISSUE TITLE
Specification 1

### ISSUE THREAD

**Issue by MAChitgarha** [semver/semver#459]
First, I'm going to include it here:
> Software using Semantic Versioning MUST declare a public API. This API could be declared in the code itself or exist strictly in documentation. However it is done, it should be precise and comprehensive.

1. Could an API be GUI? Is it mentioned here? If so, where? 
1.1. If we can declare a project's API to it's User Interface, then changes to the code without any impacts in GUI would be ignored from versioning, because it's out of API. It seems worse not to version a change. So, what?
1.2. If a GUI is a true definition of an API, then I don't understand a precise and comprehensive GUI. A precise GUI? A comprehensive GUI? I have no idea!

Thanks!

**Comment by jwdonahue** [comment]
@grv87, yes. I personally don't run the show here, but I'd prefer to answer questions in SO, and there are more people there to help out than there are here. I've been trying for almost a year to get the list of issues here down to something like an actionable set of proposed changes, while trying to convince folks to close their own threads when their questions seem to have been answered or their proposals are unlikely to be accepted.

That said, I don't mind answering questions, provided we can get them answered and closed quickly.

**Comment by MAChitgarha** [comment]
Thank you @jwdonahue, I'll check that thread later.

@grv87! What about adding comments to the code? It doesn't have any impacts on the output, but it's a _change_, so you can't ignore it (e.g. by merging it to a future change). Missing comments (for future references or working as a team) is not an _incorrect behaviour_ related to the defined API, which is GUI.

**Comment by MAChitgarha** [comment]
As you know, _by_ varies from _in_. So, _by the code_ not equals _in the code_.

From SemVer:
>  For this system to work, you first need to declare a public API. This may consist of documentation or be enforced by the code itself.

In the first specification, we read:
> Software using Semantic Versioning MUST declare a public API. This API could be declared in the code itself or exist strictly in documentation.

I think in the specification the word _in_ should be changed to _by_. Then, we can say "OK, GUI is an API". _By the code_ has a larger definition instead of _in the code_. From my opinion, we cannot say defining GUI in the code, but by the code. Am I wrong?

**Comment by MAChitgarha** [comment]
I'm going to close this thread, but in my head, this question is still open. Either I can't say what I mean or you can't or don't want to accept. If I'm wrong, you don't tell where.
BTW, thank you all.

**Comment by klehelley** [comment]
I guess jwdonahue's reaction is due to the last two comments that precede his. Your first question, "Could an API be GUI?" is completely OK, though a little imprecise regarding the situation described in 1.1 (I am not sure whether I'd be on point or not if I tried to answer it).

However, your answer to grv87 makes it look like you haven't put much thought into his answer, or haven't understood it. (And your example of having a release that differs only from the previous one by comments is hardly a compelling one. Nobody does that; except in the context of Continuous Deployment -- in which case SemVer is probably a bad choice of versioning scheme.)

And the message following it makes no sense, in that it seems to be advocating that some content in version 1.0.0 of the specification should be changed to something that is already present in 2.0.0. I am not really sure why you are actually caring about version 1.0.0 of the specification, as far as I know it is not maintained (i.e. do not expect a version 1.0.1 or 1.0.0 anytime soon), and if changes are to be made they should refer to version 2.0.0 of the specification.

---

Regarding using SemVer for GUI, my 2 cents: it is extremely hard to define what a breaking change is in regard to the users. The good thing with API consumption is that either it works or it does not, no middle ground here. But with GUI one user may adapt to a modification with little effort, while another for the same change could end up completely lost and unable to continue without a lot of efforts. For that reason using SemVer as-is for GUIs is a lot of hassles. But it may work if you define precisely what kind of changes should result in which number being bumped. Ask yourself the question also of who will consume that version number and how it will help them, and whether SemVer is the right choice for them.

**Comment by MAChitgarha** [comment]
@klehelley, thanks for your comments!
Version 1.0.0 of specification? No, I mean the first rule/spec of the Semantic Versioning Specification part, as I included it in my question.

Maybe I'm doing the wrong stuff, but why you should not have two versions that differ by comments? For example, if you forget to add comments when you code, you may want to add whole missing comments. We all know it's a common error. Consider we are using Git, shouldn't I commit that change? If I shouldn't do that, what should I do instead? Please help me in this case. Again, maybe I'm doing a wrong thing.

**Comment by jwdonahue** [comment]
@MAChitgarha said:

> 1.1. If we can declare a project's API to it's User Interface, then changes to the code without any impacts in GUI would be ignored from versioning, because it's out of API. It seems worse not to version a change. So, what?

Did the bits change in the package that delivered that GUI? If so, you have a new version and at least a patch increment. If no bits changed, there's no new version, assuming you have the non-existent repeatable build system. Most build systems claim determinism, but they include inputs that affect the output which are not part of the source code (dates, times, machine/user names, paths, log-file names, etc), so they cannot produce the same package from one build to the next, even if none of the compile-able code changed (ie, you only made comment changes).  If the bits in the package are different, you have a new version.

**Comment by jwdonahue** [comment]
I will add that truly deterministic build systems, always produce the same output no matter the machine, user, time, date or system configuration (did I miss anything?) at the time of the build.  As far as I know, there's never been any such build system in the history of computing.  Some projects have attempted it, but all of them that I am aware of have thus-far missed the mark.

Hence, every build should always produce a package with a new version tag on it.

**Comment by MAChitgarha** [comment]
@jwdonahue, thank you for your explanation.

Now I want to know why you didn't accept changing _in the code_ to _by the code_, as I mentioned it [here](https://github.com/semver/semver/issues/459#issuecomment-414430820), and you said "you seem to be trolling"?

**Comment by jwdonahue** [comment]
@MAChitgarha, oh, I just edited it twice by the way. I usually don't encounter anyone online here this late at night.

**Comment by jwdonahue** [comment]
@MAChitgarha, you're wearing me down man. If you want to provide a pull-request for a specific change, please do so. I won't support that change because it just doesn't sit well with me.  I think [it's a nit](https://www.dictionary.com/browse/nit?s=t) at best.

**Comment by jwdonahue** [comment]
@MAChitgarha, please take your questions to[stackoverflow](https://stackoverflow.com).  I am trying to reduce the noise level here so we can focus on actionable issues. User support is better handled on SO.

**Comment by MAChitgarha** [comment]
@jwdonahue, OK, thank you!

**Comment by jwdonahue** [comment]
@MAChitgarha, can you please close this issue at your earliest possible convenience?  Thank you.
