### ISSUE TITLE
Non-prerelease Versions Should Not Be Allowed to Use Prerelease Versions of Dependencies

### ISSUE THREAD

**Issue by Swivelgames** [semver/semver#479]
There's a growing trend of projects being published under semver that depend on pre-release dependency versions, that cause compatibility issues as time goes on and those projects move out of pre-release. This is causing projects to "unknowningly" release versions that become incompatible and breaking later on due to their dependency on these pre-release versions.

No stable version should have a pre-release dependency, as that tarnishes the definition of "stable".

In my opinion, this should be dictated by semver. It's becoming a major problem for developers trying to work within a stable environment. Semver has already helped tremendously in alleviating these types of problems by properly defining versioning to prevent issues like this from occurring. This would be a huge leap in the right direction as we all continue to work towards ensuring stability in our projects.

**Comment by grv87** [comment]
I don't see the harm if the project's release used exact version of pre-release dependency.
The real problem is that the project should have been re-released when dependency reached stable stage.

**Comment by remona-minett** [comment]
If a version of a dependency is pre-release, wouldn't the inclusion in a release build also constitute that the dep is release worthy? Therefore, everything including deps should be moved to at least 1.0.0?

**Comment by runeimp** [comment]
Nothing about the state of your API, app, etc. should indicate anything about the state of its dependencies. The state of your product is the only thing that matters. If you feel your product is release worthy (pre-release or otherwise) that's your call. If a dependency is implemented in a way that it's version could change at a later date and then make your product fail should be avoided by locking the version of the dependency if your worried about such things. It may also be completely reasonable to assume that allowing the dependency to be upgraded at a later date is desirable. These are simply judgement calls based on many factors of the development process and the understanding of how your audience may use your product. And sometimes you can do everything as safe as possible and things still break down the line for reasons far beyond your control. There is no perfect system. SemVer is just a great start in trying to create a better system that most developers should be able to follow.

**Comment by alexandrtovmach** [comment]
👻 👻 👻 
Closed as staled

**Comment by alexandrtovmach** [comment]
Closing as staled, feel free to re-open or create a new issue :ghost:

**Comment by ljharb** [comment]
@alexandrtovmach closing?
