### ISSUE TITLE
Sad CSS?

### ISSUE THREAD

**Issue by hartwork** [semver/semver#482]
Hi!

Why is the current CSS so sad and all black(, grey) and white?
What are your requirements for pull request touching CSS to be more friendly?

Thanks and best, Sebastian

**Comment by trustgit** [comment]
Hi,

Different people have different views on styles, therefore changes in CSS aren't necessary unless they make better accessibility.

After all semver.org is just a site for presenting a specification so the point is to make things clear instead of fancy, and the current CSS is doing the job well.

*PS* You can fork [semver/semver.org](https://github.com/semver/semver.org) and open a pull request if you don't want to change your mind.

Ren

**Comment by hartwork** [comment]
Hi Ren,

I have started playing with things a bit and come to realize that the markdown sources miss use of single backticks for code in general and for all translations. To really get somewhere shiny, that would be needed. So that pile of work made me decide to not try much further and to limit myself to [fixing a few smaller issues](https://github.com/semver/semver.org/pulls?q=is%3Apr+author%3Ahartwork+), only, for now.

**Comment by hartwork** [comment]
PS: I should have mentioned that https://keepachangelog.com/en/1.0.0/ is a good example of what I would wish for https://semver.org/ visually, instead.

**Comment by klehelley** [comment]
While it may be beneficial to pimp up semver.org a little bit, keepachangelog.com is probably not such a good example. It sure looks nice, but with the variety of sections and colours it is a little too distracting to my taste. Other may disagree though.

**Comment by hartwork** [comment]
I agree about the distraction part to some extent. I'll leave to other to judge if the added fun it provides is worth a few bits of distraction or not.

**Comment by steveklabnik** [comment]
Hi, this repository is for the specification itself; website bugs should go over at https://github.com/semver/semver.org. Thanks!
