### ISSUE TITLE
Request to be a maintainer

### ISSUE THREAD

**Issue by alexandrtovmach** [semver/semver#536]
In both repos we have a lot of staled issues and PR's:
https://github.com/semver/semver.org
https://github.com/semver/semver

I'd be happy to help with that, but I need maintainers rights.

Could someone help with that?

**Comment by jwdonahue** [comment]
See the [SemVer Team section of the Contributing.md file](https://github.com/semver/semver/blob/master/CONTRIBUTING.md#the-semver-team) regarding maintainers.

You can always do what I have done, and @OP a reply to get the original poster to close out their threads.  When I first started doing that a few years back there were a couple hundred of them.  The current maintainers are all language/package tooling stakeholders.

**Comment by steveklabnik** [comment]
Yep, I’ve been slowly going through things, but haven’t had as much time recently. I plan on picking things up again soon.

Moving slowly is good for specifications; there’s no rush here.

**Comment by jwdonahue** [comment]
@steveklabnik, from what I can tell, you are doing a pretty good job.  We've been holding the ~80 issues range for a long time and I haven't been putting in anywhere near the time I used to.  Pretty sure that I've either requested closure or promotion of every open thread that is more than 6 months old.  But there are some sticky issues that I think should be killed off with an official "never going there" statement. How likely is it that SemVer would ever be extended to cover 4 or more version fields?

A doc covering minimal requirements for a v3 proposal would be a good way to quash a lot of old v3 proposals.  For instance, any proposal that doesn't solve the SemVer version string ambiguity issue should be dismissed as incomplete. 

Personally, I am betting on [VersionMeta](http://versionmeta.org) and [VersionSchema](http://versionschema.org) to supersede SemVer over the next eight to ten years or so.

**Comment by steveklabnik** [comment]
Yes, I agree that a “we’re not doing this” document of sorts would be good. I have not found the time to write such a thing up and solicit feedback from the other maintainers yet. But it’s on my list.

**Comment by alexandrtovmach** [comment]
@jwdonahue @steveklabnik Thank you for responses. I also agree with statement "moving slowly is good for specifications", but I don't want to change something especially in spec, I just want to resolve a ton of issues and PRs about "typos, mistakes, translations"

**Comment by alexandrtovmach** [comment]
@anangaur @dherman @indirect  @isaacs @segiddins @steveklabnik 
Sorry for ping, I tagged all of you from the list [here](https://github.com/semver/semver/blob/master/CONTRIBUTING.md#the-semver-team)

As you can see from this issue — I want to be a maintainer, but my focus is not to change the specification. I just want to help with issues and PR's related to translations, typos, formatting and probably code updates. Here is a lot of them:
- https://github.com/semver/semver.org/pull/237
- https://github.com/semver/semver.org/pull/238
- https://github.com/semver/semver.org/pull/239
- https://github.com/semver/semver.org/pull/240
...etc.
I totally understand that you guys haven't free time to work with that, but I have time and I enjoy it =)

**Comment by indirect** [comment]
I'm in favor 👍

**Comment by jwdonahue** [comment]
@alexandrtovmach, do you comprehend any of those languages?

**Comment by alexandrtovmach** [comment]
@jwdonahue Not sure, do you asking about languages to translate? Yes, I'm native speaker for Russian and Ukrainian

**Comment by alexandrtovmach** [comment]
@anangaur @dherman @isaacs @segiddins @steveklabnik
friendly ping =)

**Comment by segiddins** [comment]
I 👍 'd @indirect's reply a few months ago ;)

**Comment by alexandrtovmach** [comment]
@segiddins thank you, but could someone add me maintainer rights to repo?))

**Comment by alexandrtovmach** [comment]
ping

**Comment by alexandrtovmach** [comment]
⏲️ ping ping

**Comment by alexandrtovmach** [comment]
@anangaur @dherman @indirect @isaacs @segiddins @steveklabnik
If there are no objections, could someone give me a maintainer rights, so I can manage issues and PRs?

**Comment by runeimp** [comment]
I realize that the owners (@anangaur @dherman @indirect @isaacs @segiddins @steveklabnik) are probably very busy and SemVer is very low priority for them at this point (not that they don't continue to contribute). I realize that the world around us seems to be crumbling due to COVID-19. But seriously!

1. @alexandrtovmach has been requesting maintainer rights for almost a solid year.
2. There have been ZERO public objections to his making the changes he's suggesting.
3. There has, in fact, been consensus from 3 of the 4 maintainers of the repo.
4. He will die of old age at some point
5. Sooner than that his good will, enthusiasm, and desire to contribute may be diverted elsewhere and that resource lost to this project. I'd suspect such a resource would be considered quite valuable.
6. This behavior makes the project seem dead or dying.
7. SemVer dying and not yet being superseded by something like [VersionMeta](http://versionmeta.org/) or [VersionSchema](http://versionschema.org/) for long term adherants to the spec like myself is very disheartening.

I expected this issue to languish for a few months. I get it, everyone is busy, and no one wants to deal with the aftermath if things go wrong. What else is needed to resolve this before we hit the first anniversary of it's submittal, or as it seems to be going, the second, or third anniversary?

**Comment by indirect** [comment]
@alexandrtovmach you have the patience of a saint, and I apologize for the long delay. Check your email for an invitation to semver/semver and semver/semver.org.

@runeimp your post is inflammatory, and absolutely in violation of this project's [code of conduct](https://github.com/semver/semver/blob/master/CODE_OF_CONDUCT.md). If you continue in this manner, expect a ban from this GitHub organization's repositories. Instead, please apologize and try to post with more empathy in the future.

**Comment by alexandrtovmach** [comment]
@indirect Thank you for invite :+1: I'm finally get it :tada: :tada: :tada: 

@runeimp it seems like you tried to support me, thank you, but I agree with @indirect that looks a bit rude, but I believe you don't mind anything bad, right?

**Comment by jwdonahue** [comment]
@runeimp 's comments were spot-on, and seemed quite gentle to me.  I can empathize somewhat with the maintainers.  It's hard finding time for this sort of thing when you have a day job and I know from personal experience how the CoVid19 crises can really mess with well planned schedules.

Still, I think an application to the maintainers list should be rejected or accepted within a reasonable period of time.  I think PR's should be accepted or tagged and rejected within a reasonable period of time as well.  This site is showing signs of mortality.  It used to be we only had to get the attention of one maintainer to get some traction now and then, now we have to get the attention of the entire group of maintainers and hope enough of them can be bothered to reach a consensus and at least one of them acting on it.

**Comment by runeimp** [comment]
@alexandrtovmach I'm glad you are finally getting the access you requested. I look forward to your contributions.

@indirect I am a very empathetic person. I do _not_ enjoy being rude or inflammatory in any way. It was in fact rather painful to write the comment in question. More so because I felt the need to be so blunt in order to get things moving. Even more so because it puts into stark contrast the difference between my early interactions with the project and what is has become today. I don't want to see this project _die on the vine_ when it was bearing fruit before I ever heard of it and I feel it's just as relevant now as it was then, so many years ago. Aside from all of that, thank you for giving @alexandrtovmach the access he was requesting.

**Comment by indirect** [comment]
@jwdonahue your feedback about what you consider gentle is appreciated. However, sarcastic attacks on the maintainers are not acceptable here, whether or not the maintainers are doing what you consider to be a good job.

@runeimp It's valid to feel like you need to be blunt. It is also clear both in the code of conduct and in my previous message that your tone and language is not acceptable here, regardless of how you feel about the project or the maintainers. Since you decided to defend your violation instead of apologizing and agreeing to follow the CoC in the future, I am awarding you a one week ban.

Please follow the code of conduct after that week is up, so we can collaborate productively from that point forward.

**Comment by jwdonahue** [comment]
@indirect, Sir, please add me to the ban list as well.  I will happily wear that badge proudly and loudly.

- The word "sarcasm" is not mentioned anywhere in the [Code of Conduct](https://github.com/semver/semver/blob/master/CODE_OF_CONDUCT.md).  
- Nowhere does it mention that putting up a defense of ones views is unacceptable.
- @runeimp does not oh you an apology, in fact, it's the other way around. They should not have had to even bring up the subject in the first place.

As a maintainer, you are free to be as arbitrary as you like, so you might as well ban me too and make it permanent.

@haacked FYI.

**Comment by ljharb** [comment]
> Other conduct which could reasonably be considered inappropriate in a professional setting

**Comment by indirect** [comment]
Just in case anyone needs a detailed breakdown of the ways that the comment violated the code of conduct, I wrote them in reply to @jwdonahue's issue #571. I'm going to lock this ticket now, and hopefully we can move on to other, more productive, things.
