### ISSUE TITLE
Request clarity on this site's code of conduct.

### ISSUE THREAD

**Issue by jwdonahue** [semver/semver#571]
[This reply](https://github.com/semver/semver/issues/536#issuecomment-640972146) to [this thread](https://github.com/semver/semver/issues/536#issue-499406637), prompted [this reply](https://github.com/semver/semver/issues/536#issuecomment-641118920) from a maintainer.  I would really like to know specifically which rule(s) in the code of conduct were violated.  I see no apparent violation.

Given that one of the precious few responses from the maintainers, in recent months, happens to include a rebuke, I think it's important that we clear this up right away.

**Comment by indirect** [comment]
The code of conduct explicitly requests:

- Using welcoming and inclusive language
- Focusing on what is best for the community
- Showing empathy towards other community members

The code of conduct explicitly forbids:

- insulting/derogatory comments
- public or private harassment
- other conduct which could reasonably be considered inappropriate in a professional setting

The comment that you linked to is not welcoming or inclusive, does not focus on what is best for the community, does not show empathy towards other community members, includes multiple derogatory comments, explicitly at-mentions every maintainer on a hostile message, and is not appropriate for a professional setting.

In particular, the bits about "He will die of old age at some point" and "the first anniversary of it's submittal, or as it seems to be going, the second, or third anniversary?" are especially unnecessary and hostile to the volunteer maintainers.

As always, please follow the code of conduct when posting or otherwise interacting with this repository.

**Comment by jwdonahue** [comment]
Bye!

**Comment by jeme** [comment]
@indirect I think this particular case was handled extremely poorly, and I am sorry that that calls you out...

I can understand that those particular sentences could be seen as not in line with the COC, however they are not in my eyes of a particular harmful nature. They were just not very constructive.

Calling out for an apology directly and when that was not received, issuing a temporary ban would certainly not be in line with the COC if you ask me... AS the COC states the following:

----
Project maintainers are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behavior.
----

I don't think "Appropriate" or "Fair" action is the words I would describe for what was done here...

A warning would perhaps been in it's place. But this was taken to far... And I would encourage that the entire team would discuss this now, as in line with the COC.
