### ISSUE TITLE
Can you modify versioned prereleases?

### ISSUE THREAD

**Issue by CidTori** [semver/semver#802]
The FAQ states that "it is unacceptable to modify versioned releases", but is it acceptable to modify versioned _pre_-releases?
For example, can you reuse version 1.2.3-alpha (or 1.2.3-SNAPSHOT) until it's stable enough, or do you _need_ to increment it (1.2.3-alpha.1, 1.2.3-alpha.2, …) each time you make a change?
If both are acceptable, are their best practices (like maybe you can reuse alphas but not betas or rcs since they're public)?

**Comment by ljharb** [comment]
Prereleases are themselves still releases, so no.

**Comment by CidTori** [comment]
Does it mean that Maven's SNAPSHOTs aren't SemVer compliant?

**Comment by Saklad5** [comment]
If you want something to be subject to change, simply avoid giving it a version in the first place. This is why versions are generally represented as tags in Git: they are permanently assigned to a specific commit.

In light of this, by the way, I actually recommend against referencing the current version in anything under source control: any commit that doesn’t update it would violate SemVer.

---

Swift Package Manager has an approach I’m quite fond of: if users want to specify dependencies that can change like that, they use a [Git branch](https://developer.apple.com/documentation/swift_packages/package/dependency/requirement) instead of a semantic version. If a package actually does this, other packages can’t depend on specific versions of it: that means you don’t have to worry about a dependency doing it.

**Comment by Udik2021** [comment]
> The FAQ states that "it is unacceptable to modify versioned releases", but is it acceptable to modify versioned _pre_-releases?
> For example, can you reuse version 1.2.3-alpha (or 1.2.3-SNAPSHOT) until it's stable enough, or do you _need_ to increment it (1.2.3-alpha.1, 1.2.3-alpha.2, …) each time you make a change?
> If both are acceptable, are their best practices (like maybe you can reuse alphas but not betas or rcs since they're public)?

**Comment by Udik2021** [comment]
> The FAQ states that "it is unacceptable to modify versioned releases", but is it acceptable to modify versioned _pre_-releases?
> For example, can you reuse version 1.2.3-alpha (or 1.2.3-SNAPSHOT) until it's stable enough, or do you _need_ to increment it (1.2.3-alpha.1, 1.2.3-alpha.2, …) each time you make a change?
> If both are acceptable, are their best practices (like maybe you can reuse alphas but not betas or rcs since they're public)?

**Comment by jwdonahue** [comment]
> they are permanently assigned to a specific commit

That is difficult to enforce. Git tags should generally be considered malleable.  Tagging commits with version  numbers does not scale well. Versioning should be done on the backend of the build.

**Comment by steveklabnik** [comment]
In general, semver's perspective is that releases are immutable.
