### ISSUE TITLE
Increasing major version without incompatible change

### ISSUE THREAD

**Issue by mkarg** [semver/semver#946]
SemVer says that the major version MUST get increased when there is an *incompatible* change. Understood.

But MAY the the major version get increased *without* an incompatible change? For example, for marketing reasons a company likes to increase the major version every year, even if all features still are backwards compatible.

**Comment by ljharb** [comment]
Yes, it may, but doing it for marketing reasons is not a good idea, since that’s not what semver is for.

**Comment by JohnTitor** [comment]
Yeah, SemVer gives "semantics" to versioning for API/code changes, and market reasons aren't its target, I think.

**Comment by steveklabnik** [comment]
I would agree that doing so is acceptable. I think how harmful it is comes down to the specifics of your case; if there aren't any breaking changes, and you bump major, your users will have to do some work to upgrade to it, whereas it would have been a transparent upgrade otherwise. How bad that is for you is relative.

A similar situation: I've sometimes bumped major or minor when I am *unsure* if I am required to or not, because in some senses, that's the conservative case. Over-advertising breakage is better than under-advertising it.

**Comment by mkarg** [comment]
Thank you all for your comments, they are appreciated! In fact, I possibly was not clear enough. The target of this issue is not to collect single opinions or pros and cons, but to get an *official, authoritateive* answer of the SemVer Spec Team whether doing so would *definitively violate* SemVer spec *or not*.

**Comment by ljharb** [comment]
@mkarg definitively, it would not definitely violate semver, per two Semver Spec team members above. I'd argue it violates the _spirit_ of semver, and is a gross and icky thing to do, but neither of those are definitive/objective nor answered by the spec.
